### ISSUE TITLE
SSL authentication: "x509: certificate signed by unknown authority"

### ISSUE THREAD

**Issue by aodj** [cloudhut/kowl#104]
I'm trying to setup the TLS/SSL authentication but keep receiving the error `"Failed to connect to broker kafka-0:19092: x509: certificate signed by unknown authority"`

I'm using Hashicorp Vault to generate the certificates, and have no problems with other applications and these certificates for Kafka, so I'm not sure where to begin debugging.

Do you have a worked example with TLS enabled?

fwiw, running the `openssl verify` command returns OK:

```bash
$ openssl verify -verbose -CAfile ca_bundle.pem kowl.pem
kowl.pem: OK
```

**Comment by weeco** [comment]
Hm if you provide the right CA for your self signed certificates this should work and there shouldn't be any need to enable `InsecureSkipVerify`. Did you configure a path to your CA file? https://github.com/cloudhut/kowl/blob/master/docs/config/kowl-business.yaml#L26

The relevant code for the TLS connection configuration is this: https://github.com/cloudhut/kowl/blob/master/backend/pkg/kafka/connection_helper.go#L29-L58 . As you can see in line 39-41 the provided CA is simply appended to the default cert pool and therefore I believe this should not be a problem.

**Comment by aodj** [comment]
> Did you configure a path to your CA file? https://github.com/cloudhut/kowl/blob/master/docs/config/kowl-business.yaml#L26

This was the problem; I'm using an existing secret, and assumed that by setting the existing secret it the Helm chart would tie it all together for me (since all the keys are required). Once I defined the `caFilepath`, `certFilepath`, and `keyFilepath` keys in the config, my pod started successfully.

**Comment by weeco** [comment]
I agree this part of the Helm chart is not user friendly enough. I am not entirely sure if we can change the chart so that it becomes more transparent but at the least we can probably improve the documentation for that. I'll create a separate issue for this.
