### ISSUE TITLE
What is the minimum supported Kafka version?

### ISSUE THREAD

**Issue by dpavlov-smartling** [cloudhut/kowl#105]
I assume this should be related to supported versions of Sarama Go library, but could you please clarify. 

Thanks,

**Comment by weeco** [comment]
Currently it is v1.0.0. We could easily add support for 0.11+ the only feature we need v1.0.0+ for is calculating the log size / topic sizes. We don't want to go below 0.11 given the age and big changes introduced with 0.11

**Comment by dpavlov-smartling** [comment]
Thank you @weeco for clarification.
