### ISSUE TITLE
Add option to download all search results

### ISSUE THREAD

**Issue by weeco** [cloudhut/kowl#110]
I may want to download all kafka message from the search results as CSV, JSON, ... so that I can work with that.

**Comment by rikimaru0345** [comment]
Just to clarify: the idea is to save all messages that the browser **has currently loaded**; not to "stream" results into a file (which is closely related, but not what is meant here).

**Comment by rikimaru0345** [comment]
closed by 453b9fbbfeda8c2054c0bb048299f567bffe3011
