### ISSUE TITLE
Show detected message encoding in message response

### ISSUE THREAD

**Issue by weeco** [cloudhut/kowl#112]
The backend returns the detected message encoding for each kafka message. The frontend currently doesn't show this encoding. Adding a badge or similar would be nice.

**Comment by rikimaru0345** [comment]
adding it is easy

- where you want it shown? (make screenshot and scribble into it 😄)
- when should it be displayed? always? (i guess so)  or only when there are at least two messages with different encodings? (which is extremely rare, who mixes for example json and avro in the same kafka topic 😂)
