### ISSUE TITLE
Allow to delete an Empty Consumer Group

### ISSUE THREAD

**Issue by julienlafont-tabmo** [cloudhut/kowl#115]
**Usecase**

I'd like to be able to delete an empty consumer-group, that is any consumer-group that has no active members. 
These staled consumer-groups have their lags growing forever and will create false-positive in lag monitoring tools.

A confirmation popup could be displayed before deleting the consumer-group (destructive command)

**Comment by weeco** [comment]
Makes sense and your usecase is somewhat related #95 as well because a consumer group also may just stop to consume one of three topics which would cause ever growing lags as well.

**Comment by weeco** [comment]
Fixed via https://github.com/cloudhut/kowl/commit/7931c138410ad17bc22c9c1c1afabcc047c204d8
