### ISSUE TITLE
Kowl Installation.

### ISSUE THREAD

**Issue by manojkumarsadhu** [cloudhut/kowl#129]
How to install kowl in local. could you please provide all the steps to install and run the kowl

**Comment by rikimaru0345** [comment]
The easiest way would probably be to use one of the built docker images.
https://quay.io/repository/cloudhut/kowl?tab=tags

Mount your config and pass credentials as parameters.
Check out this page for details: https://github.com/cloudhut/kowl/blob/master/docs/installation.md

Let me know if you're running into any issues.

Also, we eventually want to provide a self-contained docker image that contains kowl, a small kafka cluster, and a tool to produce some example topics/messages. That will probably make things a bit easier. However, I can't really say when we'll get around to do that.

**Comment by manojkumarsadhu** [comment]
Hi,
I pull docker image from https://quay.io/repository/cloudhut/kowl?tab=tags.
But my question how to run that by using my kafka ip and port. could you
send me commands to run.


Thanks & Regards

Manoj

**Comment by rikimaru0345** [comment]
There is a docker compose example here that starts zookeeper, kafka brokers, and kowl.
https://github.com/cloudhut/kowl/blob/master/docs/local/docker-compose.yaml
https://github.com/cloudhut/kowl/blob/master/docs/local/config.yaml

Run it with `docker-compose up`
Does that help?

**Comment by suhyunjeon** [comment]
It's simple. That's it.
```
$ cd /kowl/docs/local 
$ docker-compose up
```

```
kafka1_1  | [2020-11-01 04:22:32,806] INFO [Log partition=__confluent.support.metrics-0, dir=/var/lib/kafka/data] Loading producer state till offset 0 with message format version 2 (kafka.log.Log)
kowl_1    | {"level":"info","ts":"2020-11-01T04:22:32.959Z","msg":"connecting to Kafka cluster"}
kafka1_1  | [2020-11-01 04:22:32,972] INFO [Log partition=__confluent.support.metrics-0, dir=/var/lib/kafka/data] Completed load of log with 1 segments, log start offset 0 and log end offset 0 in 311 ms (kafka.log.Log)
kafka1_1  | [2020-11-01 04:22:33,006] INFO Created log for partition __confluent.support.metrics-0 in /var/lib/kafka/data/__confluent.support.metrics-0 with properties {compression.type -> producer, message.downconversion.enable -> true, min.insync.replicas -> 1, segment.jitter.ms -> 0, cleanup.policy -> [delete], flush.ms -> 9223372036854775807, segment.bytes -> 1073741824, retention.ms -> 31536000000, flush.messages -> 9223372036854775807, message.format.version -> 2.5-IV0, file.delete.delay.ms -> 60000, max.compaction.lag.ms -> 9223372036854775807, max.message.bytes -> 1048588, min.compaction.lag.ms -> 0, message.timestamp.type -> CreateTime, preallocate -> false, min.cleanable.dirty.ratio -> 0.5, index.interval.bytes -> 4096, unclean.leader.election.enable -> false, retention.bytes -> -1, delete.retention.ms -> 86400000, segment.ms -> 604800000, message.timestamp.difference.max.ms -> 9223372036854775807, segment.index.bytes -> 10485760}. (kafka.log.LogManager)
kafka1_1  | [2020-11-01 04:22:33,023] INFO [Partition __confluent.support.metrics-0 broker=1] No checkpointed highwatermark is found for partition __confluent.support.metrics-0 (kafka.cluster.Partition)
kafka1_1  | [2020-11-01 04:22:33,026] INFO [Partition __confluent.support.metrics-0 broker=1] Log loaded for partition __confluent.support.metrics-0 with initial high watermark 0 (kafka.cluster.Partition)
kafka1_1  | [2020-11-01 04:22:33,030] INFO [Partition __confluent.support.metrics-0 broker=1] __confluent.support.metrics-0 starts at leader epoch 0 from offset 0 with high watermark 0. Previous leader epoch was -1. (kafka.cluster.Partition)
kowl_1    | {"level":"info","ts":"2020-11-01T04:22:33.054Z","msg":"Server listening on address","address":"[::]:8080","port":8080}
kafka1_1  | [2020-11-01 04:22:35,087] INFO Successfully submitted metrics to Confluent via secure endpoint (io.confluent.support.metrics.submitters.ConfluentSubmitter)
kowl_1    | {"level":"info","ts":"2020-11-01T04:22:36.068Z","msg":"connection to all brokers healthy","brokers":1}
kafka1_1  | [2020-11-01 04:22:36,791] INFO [Controller id=1] Processing automatic preferred replica leader election (kafka.controller.KafkaController)
```

**Comment by manojkumarsadhu** [comment]
I added my kafka Servers in docker-compose.yaml file. but i am getting below error
kowl_1    | {"level":"info","ts":"2020-11-10T09:46:30.489Z","msg":"not connected to all brokers","connected":0,"brokers":3}
brokers are available but they are not connecting

**Comment by weeco** [comment]
@manojkumarsadhu You can enable the debug logs for more precise information.

Generally we can't help you debugging your Kafka setup or Docker network though. If you just want to test Kowl I recommend you to stick to the original docker-compose as this setup has been created and tested by us.

**Comment by manojkumarsadhu** [comment]
Step 16/39 : RUN test -n "$KOWL_GIT_SHA" || (echo "KOWL_GIT_SHA must be set" && false)
 ---> Running in cf4073c00c13
KOWL_GIT_SHA must be set
The command '/bin/sh -c test -n "$KOWL_GIT_SHA" || (echo "KOWL_GIT_SHA must be set" && false)' returned a non-zero code: 1

**Comment by rikimaru0345** [comment]
> Step 16/39 : RUN test -n "$KOWL_GIT_SHA" || (echo "KOWL_GIT_SHA must be set" && false)
> ---> Running in cf4073c00c13
> KOWL_GIT_SHA must be set
> The command '/bin/sh -c test -n "$KOWL_GIT_SHA" || (echo "KOWL_GIT_SHA must be set" && false)' returned a non-zero code: 1

When building the docker image yourself you need to set a few arguments.
For testing/debugging/trying out Kowl you can just set anything:

```
--build-arg "KOWL_GIT_SHA=abc123testtesttest"
--build-arg "KOWL_GIT_REF=debug"
--build-arg "KOWL_TIMESTAMP= 1605012895"
```

The only assumptions about those values are:
- `KOWL_GIT_SHA` should be at least 8 characters long (because the frontend assumes a full length hash and will try to cut it)
- `KOWL_TIMESTAMP` should be a number (frontend will parse it to display the build timestamp)

**Comment by fferraro87** [comment]
hi,
i've tried to use on my kafka cluster so i've done this steps :
`docker run quay.io/cloudhut/kowl:v1.2.1 --config.filepath=/root/kowl_config.yml`
but i've that error : 
`{"level":"info","msg":"started Kowl","version":"v1.2.1","built":"2020-11-16T15:03:00Z","git_sha":"a89848367df0c94cee64aa15345ed720fb17e83e"}
{"level":"fatal","msg":"failed to load yaml config","error":"error reading config file: open kowl_config.yml: no such file or directory"}`
i've created /root/kowl_config.yml like your example file.
Where i'm wrong?

**Comment by weeco** [comment]
@fferraro87 This error message comes straight from Go and says that a file under the filepath you specified does not exist. Most likely the path is wrong or the file actually does not exist. We should add the used filepath in the error message.

**Comment by fferraro87** [comment]
@weeco sorry but i've double check, i've also change path of config file but it doesn't work as you can see (i've also try to give 777 permission to that file)
`root@110-t910 ~]# docker run quay.io/cloudhut/kowl:v1.2.1 --config.filepath=/opt/kowl_config.yml
{"level":"info","msg":"started Kowl","version":"v1.2.1","built":"2020-11-16T15:03:00Z","git_sha":"a89848367df0c94cee64aa15345ed720fb17e83e"}
{"level":"fatal","msg":"failed to load yaml config","error":"error reading config file: open /opt/kowl_config.yml: no such file or directory"}
root@110-t910 ~]# ll /opt/kowl_config.yml
-rwxrwxrwx 1 root root 2580 Nov 20 17:06 /opt/kowl_config.yml`

**Comment by weeco** [comment]
@fferraro87 Being honest here, I spent too many hours debugging such situations with users and it was almost always just some missconfigurations / user mistakes. So I won't be able to assist here, I hope you can understand that.

The relevant code that reads the file is here: 
https://github.com/cloudhut/kowl/blob/a89848367df0c94cee64aa15345ed720fb17e83e/backend/pkg/api/config.go#L70-L82

As you can see in the error log the filepath is populated to this function correctly and since this is plain Go code there's not much I could do different to read the file.
