### ISSUE TITLE
Add support for managing Kafka Connect

### ISSUE THREAD

**Issue by Zaijo** [cloudhut/kowl#131]
Hi, from what I learnt about the whole Kafka environment, many people use source / sink connectors. Yesterday I was debugging broken pipeline and Kowl didn't help me discover a failed connector task. Is it possible or is it a good place to have kowl also inspect connectors? Thanks.

**Comment by cobolbaby** [comment]
I have seen many open source implementations, only the [akhq](https://github.com/tchiotludo/akhq) supports both topic management and connector management. But its connector feature is not so good. 

If kowl supports connector management, I believe it will become the first choice for more and more Kafka users.

**Comment by weeco** [comment]
Thanks for your feedback! Do you mind describing what you'd like to see in Kowl a bit more specific so that we know what exactly we should implement / tackle? Would be nice if you could describe the usecase and the problem/inefficiency you currently face and how Kowl could help you fixing that.

**Comment by cobolbaby** [comment]
User Case:

- Kafka Connect
  - Efficiently manage multiple Kafka connect clusters, each of which runs 500+ tasks
    - I found that most of the open source implementations poll the status of each connector, instead of using the latest batch interface to obtain status.
  - Optimize list sort and display abnormal connectors first
    - Highlight abnormal connectors
  - Support front-end filtering
    - Support filter options, and support to save filter options after switching pages
    - Akhq does not implement the filtering feature, and the filtering conditions would not be temporarily stored
  - Display the failure details of the connector task including the downtime
    - Although the connect api will return the stack information of the abnormal connectors, it does not include the time point of the problem, which is not conducive to determining the scope of the problem.

**Comment by cobolbaby** [comment]
In addition:

- Kafka Topic
  - Create Topic manually
  - Display Topic create time and Support sorting by time

**Comment by avgojzack** [comment]
It would be really nice to have some aggregations here as well, the API returns things like status and worker name, which could be two cool pie charts.

**Comment by weeco** [comment]
Thanks for all your suggestions, that's awesome 🚀 🚀. I'll flesh out something and get back to you to get further feedback as we implement it. If you want to be involved in the creation process (for instance by testing / giving feedback in early versions) make sure to join our Discord server.

**Comment by cobolbaby** [comment]
@weeco  Discord server  ?

**Comment by weeco** [comment]
Hey everyone, we just merged our initial Kafka connect support. I'm aware that not all features mentioned/wished here are implemented but hopefully you will like what we added.

Feel free to submit a separate issue for your further wishes in regards to Kafka connect. Thank you all for participating and I hope to hear more feedback from you all 🔥
