### ISSUE TITLE
Option to connector schema Registry with self signed certificate

### ISSUE THREAD

**Issue by escanoru** [cloudhut/kowl#136]
Hello, 

Is it possible to connect to a schema registry which has a self signed certificate? I get the following when trying to connect to my schema registry:
`{"level":"fatal","ts":"2020-10-13T22:27:23.288Z","msg":"failed to create kafka service","error":"failed to verify connectivity to schema registry: Get \"https://172.17.17.12.com:3506/subjects\": x509: certificate signed by unknown authority"}`

Regards,
Esca!

**Comment by weeco** [comment]
Hi @escanoru ,
this is indeed not yet possible. I left a TODO comment for that back when I created the schema registry client: https://github.com/cloudhut/kowl/blob/master/backend/pkg/schema/client.go#L26

Should be easy to add though, I'll try to add it before we release 1.2 (very soon) :-).

**Comment by weeco** [comment]
@escanoru Fixed by https://github.com/cloudhut/kowl/commit/5401d2dfc27963dcbbb0f85b49069ab787fc1e17

**Comment by escanoru** [comment]
> @escanoru Fixed by [5401d2d](https://github.com/cloudhut/kowl/commit/5401d2dfc27963dcbbb0f85b49069ab787fc1e17)

Awesome! I just tried and it worked!

Thanks,
Esca
