### ISSUE TITLE
Copy buttons not working

### ISSUE THREAD

**Issue by escanoru** [cloudhut/kowl#137]
Hello Kowl team,

I noticed that when trying to copy the key value from a message the copy buttons don't work, you click on the buttons but nothing happens, I used the latest stable versions of Firefox and Chrome:
![image](https://user-images.githubusercontent.com/44711170/96300176-5a638900-0fb2-11eb-89a9-17e0a2bb293f.png)

- Esca

**Comment by weeco** [comment]
Hi @escanoru ,
I just checked the copy buttons using the version at master. Copy buttons seem to work for me. What version do you use?

Should I take care of something specific to reproduce this?

**Comment by escanoru** [comment]
Hi @weeco , 

I just realized I don't know where to check the version, I guess this is the version:
![image](https://user-images.githubusercontent.com/44711170/97339533-518f7480-1848-11eb-8ac0-6c315247335b.png)

Anyway, let me deploy the latest version and I'll let you know.

- Esca

**Comment by escanoru** [comment]
Hi @weeco,

Kafka Version: 2.4.0

Kowl connects to my cluster and works pretty well, I tried to copy the key value from one of the messages using the latest docker image and the result is the same, I may be missing something, I'm attaching a gif that shows what I'm doing

![Kowl_Copied_Buttons](https://user-images.githubusercontent.com/44711170/97351481-717a6480-1857-11eb-8821-806d03f1ba69.gif)

- Esca

**Comment by weeco** [comment]
Thanks for the details. Can you share what Browser you are using? I tried with Google Chrome, maybe it's just not compatible with all Browsers.

**Comment by escanoru** [comment]
OS: Windows 10
 Browsers tested:  
    - Chrome version: 86.0.4240.111
    - Firefox version 82.0.1 (64-bit)

**Comment by nilsroehrig** [comment]
I was not able to reproduce the issue yet, but I will try it again using Windows next.

**Comment by escanoru** [comment]
Hi @nilsroehrig,

Maybe I'm missing something, is there any condition that needs to be met before trying to copy the key or values?

-- Esca

**Comment by weeco** [comment]
@escanoru No you did everything right. Most of our test topics are actually JSON formatted, maybe that's the culprit. Could you take a look at the dev console and see if there are some error logs in the console?

I think testing non JSON encoded messages is the next thing we should test with the Copy buttons :-).

**Comment by nilsroehrig** [comment]
I think I know what the issue is. Do you run Kowl in an SSL-enabled environment? If not, the root cause lies within browser restrictions. That's because modern browsers do not allow access to the computers clipboard in unsecure environments. Can you confirm that you see an error message like `Uncaught TypeError: can't access property "writeText", navigator.clipboard is undefined` in your browsers dev console when using one of the copy buttons?

**Comment by escanoru** [comment]
Hi!

Console output:
![image](https://user-images.githubusercontent.com/44711170/97762831-66ca0480-1acf-11eb-82c3-8a2e307dc455.png)


![Kowl_Copied_Buttons](https://user-images.githubusercontent.com/44711170/97762853-6f223f80-1acf-11eb-8a74-38eaf732e444.gif)


[console.log](https://github.com/cloudhut/kowl/files/5468001/console.log)

**Comment by nilsroehrig** [comment]
@escanoru Thanks, that confirms my assumption above. For now, we don't have a solution to copy stuff from insecure connections, due to mentioned browser restrictions. But we will release a patch soon, avoiding silent fails like you experienced.

**Comment by escanoru** [comment]
That makes sense, thank you Kowl team!
