### ISSUE TITLE
Listen address support

### ISSUE THREAD

**Issue by immaro** [cloudhut/kowl#150]
Hi,
Please add a "listen address" preference (e.g.: `listenAddress`), to be able to bind, for example, to localhost only.
This apparently makes sense with reverse proxy scenarios.
Thanks in advance!

**Comment by rikimaru0345** [comment]
done:
- https://github.com/cloudhut/common/commit/ef3fe0db5b31b0488518de5992ebd787a1212604
- https://github.com/cloudhut/kowl/commit/0d2305bc127b73a782e753e77f2d0e45d79fc3f5

docker image build should be complete in a moment...
https://github.com/cloudhut/kowl/runs/1464616593
