### ISSUE TITLE
Avro deserialization is not always done

### ISSUE THREAD

**Issue by glandais-sparklane** [cloudhut/kowl#152]
If binary data starts with a [ or {, the binary data is returned as JSON

**Comment by weeco** [comment]
hi @glandais-sparklane ,
while it's true that the deserializer first checks the first character (for performance reasons), it will only be returned as JSON if the whole string can be parsed as JSON. Therefore I currently do not understand why this requires a change?

**Comment by weeco** [comment]
Closed via https://github.com/cloudhut/kowl/pull/153
