### ISSUE TITLE
SchemaRegistry error

### ISSUE THREAD

**Issue by uraniumdawn** [cloudhut/kowl#155]
Hi!
Running the docker-compose file:
`version: '2.1'
services:
  kowl:
    image: quay.io/cloudhut/kowl:v1.2.1
    restart: on-failure
    hostname: kowl
    volumes:
    - ./config.yaml:/etc/kowl/config.yaml
    ports:
    - "8080:8080"
    entrypoint: ./kowl --config.filepath=/etc/kowl/config.yaml`

with config.yml:
`kafka:
  brokers:
    - kafka-broker.somehost:9092
schemaRegistry:
    enabled: true
    urls: ["http://schema-registry.somehost:8081"]
logger:
  level: debug`

I've got the:
`{"level":"fatal","msg":"failed to load yaml config","error":"error parsing config file: yaml: unmarshal errors:\n  line 6: field schemaRegistry not found in type api.Config"}`
What did I do incorrectly?

**Comment by weeco** [comment]
It's a bit tough to figure out the indenting of your config.yml due to the formatting in this issue, but I assume you put `schemaRegistry` at the root level instead of being a child of `kafka`, see the reference config: https://github.com/cloudhut/kowl/blob/master/docs/config/kowl.yaml#L31

**Comment by uraniumdawn** [comment]
@weeco Sorry for the formatting:) Thanks a lot, Martin. This was exactly this one problem.

**Comment by weeco** [comment]
@uraniumdawn Perfect, closing the issue then. Btw there's already version v1.2.2
