### ISSUE TITLE
failed to connect to apicuro schema registry

### ISSUE THREAD

**Issue by dicolasi** [cloudhut/kowl#157]
I am trying to configure kwol to communicate with [apicuro schema registry](https://www.apicur.io/registry/docs/apicurio-registry/1.3.3.Final/index.html), but I always get this error: 

```
kowl {"level":"info","msg":"started Kowl","version":"v1.2.2","built":"2020-11-23T15:49:59Z","git_sha":"284eb140e520ee647f8801992c54e7ad05b3c0c3"}
kowl {"level":"info","ts":"2020-12-17T14:01:46.835Z","msg":"connecting to Kafka cluster"}
kowl {"level":"info","ts":"2020-12-17T14:01:46.841Z","msg":"connected to at least one Kafka broker"}
kowl {"level":"info","ts":"2020-12-17T14:01:46.841Z","msg":"connecting to schema registry"}
kowl {"level":"fatal","ts":"2020-12-17T14:01:46.864Z","msg":"failed to create kafka service","error":"failed to verify connectivity to schema registry: response is an error. Status: 404 - <html><head><title>Error</title></head><body>Not Found</body></html>"}
kowl stream closed
```

Indeed, if I forward the port it goes to svc.name/ui. Which endpoint should I point to? (tried with confluent schema registry and works perfectly fine.)

**Comment by weeco** [comment]
The client expects a schema registry that is compatible with the Confluent schema registry. More precisely this means all REST endpoints need to be available under the same path, accept the same parameters and use the same schema for the responses etc.

To check the connectivity the schema registry url + "/subjects" will be queried, see: https://github.com/cloudhut/kowl/blob/master/backend/pkg/schema/client.go#L280-L293

**Comment by dicolasi** [comment]
I see. Thanks a lot!

**Comment by estahn** [comment]
In case someone comes across this issue.

[APICurio Registry](https://www.apicur.io/registry/) has a confluent schema registry compliant API at `/apis/ccompat/v6`.

**Comment by RicardoFernandez-UY** [comment]
Hi,
@estahn And how would you configure Kowl to work with this compliant API? 
I've tried adding /apis/ccompat/v6 to the SCHEMAREGISTRY_URLS environment variable, which is suppose to point to the  schema registry URL (I'm working on Docker) and Kowl does not see it, hence it says the registry schema is not configured.
Thank you!

**Comment by guitcastro** [comment]
The apicurio schema register does not work because the [mode request](https://docs.confluent.io/platform/current/schema-registry/develop/api.html#mode) returns 404.

**Comment by weeco** [comment]
@guitcastro That should not be a problem, it should just show an error notification, but it should still work as expected. However the latest version that is pushed to master has already fixed exactly this. Could you give it a try?
