### ISSUE TITLE
Add option to display consumer group raw offsets instead of lag

### ISSUE THREAD

**Issue by smalyshev** [cloudhut/kowl#159]
Right now Kowl shows lags for consumer groups. Which is very useful but sometimes one needs also to see actual offsets. It would be useful if there was an option to switch between displaying consumer group lag and displaying the raw offsets. Maybe like Kafka tools do it:

```
GROUP           TOPIC           PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                            
ConsumerGroup   my-topic        5          11307331        11426110        118779          some-consumer-id    
```

**Comment by weeco** [comment]
@rikimaru0345 Can you add the offset as part of https://github.com/cloudhut/kowl/issues/95 ?

**Comment by rikimaru0345** [comment]
will be done together with editting consumer group offsets

**Comment by weeco** [comment]
Fixed via https://github.com/cloudhut/kowl/commit/bdaf6b1bae880da83217d82c806894917b079150
