### ISSUE TITLE
Add a file system provider to provide the proto files for Protobuf message viewing

### ISSUE THREAD

**Issue by dev501-code** [cloudhut/kowl#170]
Would be good add a file system provider to provide the proto files for Protobuf. Reasons I see the need for this.
1. Clients might have their proto files in multiple git repositories. The current git support to pull only takes one repo. Might also be a good idea to enhance git to accept a list of git repos.
2. Clients might not be using git for their repo management. Or even clients who use git repo might be using a private git. And when clients have a private git they might be supporting git with a limited set of protocols(file/ssh/https/git) etc. And the current git repo pull provided might be very limited in supporting these protocols. Also when client has their own client signed certificates, the current git provider may not work.

**Comment by abhimanyuseth-alation** [comment]
I am testing out kowl for local development and would love to have file system support for specifying the protobuf files.

**Comment by weeco** [comment]
@dev501-code @abhimanyuseth-alation 
I just pushed that into master. Here you can find the sample config: https://github.com/cloudhut/kowl/commit/29aad89cb3f9f548452d095fbc7e769d82769f36

**Comment by dev501-code** [comment]
fileSystem:
      enabled: true
      paths:
        - /etc/protos

The paths listed here under filesystem, should they be mounted onto the docker container in the docker-compose.yaml? or it is not needed?

**Comment by dev501-code** [comment]
@abhimanyuseth-alation did you try the fileSystem approach and is it working?
