### ISSUE TITLE
Problem: kowl_1  | {"level":"warn","ts":"2021-02-04T17:10:50.039Z","msg":"read from broker errored, killing connection after 0 successful responses (is sasl missing?)","source":"kafka_client","addr":"172.17.8.102:31091","id":1,"err":"connection is dead"}

### ISSUE THREAD

**Issue by dev501-code** [cloudhut/kowl#171]
I don't have any security in my kafka setup. Is it required to have some sort of security? Is there a workaround for this error?

**Comment by weeco** [comment]
@dev501-code By default it assumes plaintext (sasl is disabled), so no security mechanisms are required. It basically just means that the connection fails. Your broker logs might have more details about the reason. Can it connect to other brokers or is `172.17.8.102:31091` the address for your bootstrap server and that fails?
