### ISSUE TITLE
Kowl business - Okta - failed to validate login config: at least one login provider must be enabled

### ISSUE THREAD

**Issue by yakhyadabo** [cloudhut/kowl#174]
Hi, 

I'm trying to use kowl business with Okta authentication enabled. 
Here's the my config file : 
` 

        kafka:
          brokers:
            - kafka-0:9092
            - kafka-1:9092
            - kafka-2:9092

          tls:
            enabled: true
            caFilepath: /etc/tls/ca.pem
            certFilepath: /etc/tls/certificate.pem
            keyFilepath:/etc/tls/private_key.pem
            passphrase: xxxxxxx
            insecureSkipTlsVerify: true

        server:
          listenPort:8080
          # listenAddress:
          gracefulShutdownTimeout: 30s
          readTimeout: 30s
          writeTimeout: 30s
          idleTimeout: 30s
          compressionLevel: 4

        cloudHut:
          licenseToken: xxxxxxxxxxx
        login:
          jwtSecret: xxxxxxxxxxxxxx
          okta:
            enabled: true
            url: https://organisation.okta.com
            clientId: kowl
            clientSecret: xcxxxxxxx`

The deployment fails with the following error message : 

`{"level":"info","msg":"started Kowl","version":"master","built":"2020-12-28T12:11:46Z","git_sha":"5b135edb5f237f5600742514c001150fa93ac5fe"}
{"level":"info","msg":"started Kowl Business","version":"v1.2.3","built":"2020-12-28T12:11:46Z","git_sha":"65077b5f6b72a244239a784efc81be5c1e400956"}
{"level":"fatal","msg":"failed to validate config","error":"failed to validate login config: at least one login provider must be enabled"}`

Is there anything I have missed ? 

**versions :** v1.2.3; v1.2.4; v1.2.5

**Comment by weeco** [comment]
Hey @yakhyadabo ,
your config looks fine. I took a look at the validation logic and indeed that's an issue with the validation logic. I fixed this in master and a new build is running as I write this. In roughly 9minutes a new image should appear here: https://quay.io/repository/cloudhut/kowl-business?tab=tags

Since this is a build against master, there might be some minor issues in there.

**Comment by yakhyadabo** [comment]
@weeco I checked out your changes and the issue is sorted out. 

Thanks
