### ISSUE TITLE
kowl-business - okta - http: named cookie not present

### ISSUE THREAD

**Issue by yakhyadabo** [cloudhut/kowl#176]
Hi 

I'm having the following error when trying to login with Okta 

`{"level":"error","ts":"2021-02-16T15:41:41.834Z","msg":"Sending REST error","route":"/auth/callbacks/okta?iss=https%3A%2F%2Forganisation.okta.com","method":"GET","status_code":403,"remote_address":"11.287.93.23","public_error":"Login failed: OAuth state cookie could not be read","error":"http: named cookie not present"}
`
According to [stackoverflow ](https://stackoverflow.com/questions/55850042/how-to-fix-http-named-cookie-not-present-in-golang) it's related to the settings of the cookie. 

Is there anywhere I can set those settings ?

**Comment by weeco** [comment]
Hey @yakhyadabo ,
we set the state cookie to protect against CSRF attacks in the OAuth flow. This means we create a random string, store that string in as cookie and once you've logged in successfully with your IDP we will check whether the state cookie matches the returned state variable from the Okta redirect. This specific error indicates, that no such cookie exists for your browser. 

Could you check whether a cookie named `oauth_state` (Path: "/") exists in your client **before** authenticating against Okta? Do you possibly have some settings or browser plugins that automatically clear such cookies? For a more responsive debug session feel free to join our Discord server. I hope we can figure it out in a timely manner.

**Comment by yakhyadabo** [comment]
@weeco I don't see _**oauth_state**_ cookie in my browser. 
The only one I have is : _c15e1869894eda12f7dd7b11971f1190_

When I try to open Kowl UI from Okta I get an error window ("**Login failed: OAuth state cookie could not be read**"). 

What's the link of the Discord server ?

**Comment by weeco** [comment]
Hmm, the backend should definetely set an `oauth_state` cookie whenever you open the Kowl login interface. Do you see any error messages in the Kowl container when you open the login page?

The discord server is linked in the badges / readme: https://discord.gg/KQj7P6v

**Comment by weeco** [comment]
Hey @yakhyadabo ,
did you figure out what was going wrong there?

**Comment by yakhyadabo** [comment]
Hi @weeco, 

We have paused the experiment of **kowl business** for the moment. 
Can we use OKTA only as an Authentication backend  ?
It looks like it works as an API Gateway.

**Comment by weeco** [comment]
Hm I'm not sure what you mean by using Okta as "authentication backend". You could simply put an OAuth / OIDC proxy in front of the normal Kowl ingress if you want that.

I'd love to iron out the issues you faced though, but I haven't caught you in Discord yet. If you still have enough energy for debugging, I'm around for interactive discussions in Discord :).

**Comment by yakhyadabo** [comment]
We wanted to integrate Okta for authentication / autorisation only. 
We don't want to use it as an API gateway, because of some organisational constraints. 

I will investigate OAuth / OIDC once I have some availability.

**Comment by weeco** [comment]
> We wanted to integrate Okta for authentication / autorisation only.

That's exactly what Kowl Business is supposed to do. In order to use it for authorization (i.e. what Okta users/groups can view messages in topic x) Kowl Business is supposed to be configured with all the required Okta credentials.

I'm not sure what exactly you mean by using it as an API Gateway?

**Comment by yakhyadabo** [comment]
In this [document](https://github.com/cloudhut/kowl/blob/master/docs/provider-setup/okta.md) a new application has to be created in Okta. That's not we want to do. Our team doesn’t manage Okta. 

To make some comparison with [Hashicorp vault](https://www.vaultproject.io/docs/auth/okta) which we configure with Okta, we just provide the following details in oder to enable authentication : 
- base_url="okta.com"
- org_name="dev-123456"
- **api_token**="00abcxyz..."

We don't provide any clientId or client secret.

**Comment by weeco** [comment]
I'm not entirely sure what exactly Vault does when you integrate Okta but it looks like user credentials have to go through Vault for this to work. We want to avoid processing any actual credentials in Kowl and therefore we use Open ID connect which requires a ClientID + Client secret as described in the guide. There's no way around this.
