### ISSUE TITLE
Add logging for deserialization errors

### ISSUE THREAD

**Issue by chrisjbremner** [cloudhut/kowl#179]
I am trying to troubleshoot a display error on some of my messages that looks like this:
![display_error](https://user-images.githubusercontent.com/15189285/108536608-7f824400-7291-11eb-804a-0e9e1ee1162d.png)

In the image above, the topic has an Avro schema for both the key and message, and the key is a simple UUID, encoded as string in the schema:
```
  "fields": [
    {
      "name": "key",
      "type": "string"
    }
  ]
```

What it looks like happened is that the key fell through all of the logic in the deserializer, and got encoded as a UTF8 string, hence the leading blank spaces and the `?` symbol. I am also seeing a similar issue with the values of some messages, where the message looks like it was UTF-8 encoded, rather than deserialized using its Avro schema, and it displays the following message when I click the `+` button to view the message:
```
"ERROR":{
"message":"src property must be a valid json object"
}
```

There certainly appears to be an issue with the deserializer, as I don't see this issue using other Kafka topic viewing platforms, but I cannot pin it down without logging. Would it be possible to add logging (perhaps at a debug level) on all of the `if err == nil` checks in the deserializer that logs the value of `err` when `err != nil`?

**Comment by weeco** [comment]
Hey @chrisjbremner ,
what version are you running? I remember that someone faced (and submitted a PR to fix) an issue with priorities of the avro deserialization as well. I don't think your described hyptohesis is possibly anymore. If a schema service is specified only a JSON or XML string would have higher priority: https://github.com/cloudhut/kowl/blob/master/backend/pkg/kafka/deserializer.go#L150

See this PR: https://github.com/cloudhut/kowl/commit/49e5c3d55e74b31bfa4036a989c3b84a7a20377c#diff-65fd3dd55231fd5ed09f6eb1f8cb69822ca2e70fc0a550cf5df91ae27822292d

**Comment by chrisjbremner** [comment]
Ah, good point. I did come across that issue/change, but didn't realize it hadn't been released yet. I am running `1.2.2`, which would likely explain it. Is there a planned date for the next patch release? Would it still make sense to add logging in case the deserializer needs to be debugged in the future?

**Comment by weeco** [comment]
I think logging would be quite verbose because every consumed message would log potentially several log messages again. The next release is probably going to be 1.3.0 and not a patch release. You can by the way use the release from master (we always keep master in a deployable state): A docker image is built after every push to master: https://quay.io/repository/cloudhut/kowl?tab=tags

**Comment by chrisjbremner** [comment]
Oh, nice. I did not know that, thanks for the link. I tried out `master-c0912054` (current `master` had a rendering error) and confirmed that it now deserializes correctly. I appreciate the help and speedy response!
