### ISSUE TITLE
Uppercase strings are not supported when searching for topics

### ISSUE THREAD

**Issue by cobolbaby** [cloudhut/kowl#181]
![2021-02-23 16-09-23屏幕截图](https://user-images.githubusercontent.com/11460848/108816786-c6ee3480-75f1-11eb-875a-3c59f56909ed.png)
![2021-02-23 16-09-12屏幕截图](https://user-images.githubusercontent.com/11460848/108816810-cce41580-75f1-11eb-9430-2a5e7a579958.png)

**Comment by weeco** [comment]
Hey @cobolbaby , this has been already fixed in the master branch and will be part of the next release. If you would like to try it beforehand you can use any of our docker images that have been built against the master branch.
