### ISSUE TITLE
Make millisecond timestamps available

### ISSUE THREAD

**Issue by tewe** [cloudhut/kowl#184]
When looking at messages inside a topic, Kowl has a three-dots-menu with the command "Copy Epoch Timestamp".

Unfortunately its resolution is just seconds, when the Kafka protocol uses milliseconds.

**Comment by weeco** [comment]
Agreed, we should use unix ms instead.

Backend code: https://github.com/cloudhut/kowl/blob/910b81ffd3751b8f6d58066233daf851118db439/backend/pkg/kafka/consumer_worker.go#L48

In the frontend we have to adapt that accordingly. Should be very easy to fix.

**Comment by tewe** [comment]
Works for me. Thanks!
