### ISSUE TITLE
Cannot retrieve newest message with starting offset

### ISSUE THREAD

**Issue by tewe** [cloudhut/kowl#186]
When asked for the newest 5 messages, Kowl returns offset 44609.

![Newest 2021-03-15 at 3 05 04 PM](https://user-images.githubusercontent.com/645412/111166330-4a22fa80-85a0-11eb-9741-49b267e3e2f9.png)

But when asked for the 5 messages after 44607, it stops at 44608.

![Custom 2021-03-15 at 3 04 49 PM](https://user-images.githubusercontent.com/645412/111166352-4ee7ae80-85a0-11eb-8c89-95b530f14db4.png)

**Comment by weeco** [comment]
Can you try whether this is reproducible in latest docker images built against the master branch? We touched and refactored that code pretty heavily.

**Comment by tewe** [comment]
No change with the current image.
![Newest 2021-03-15 at 6 10 35 PM](https://user-images.githubusercontent.com/645412/111192975-f58c7900-85b9-11eb-90b9-9860aa422bac.png)
![Custom 2021-03-15 at 6 10 56 PM](https://user-images.githubusercontent.com/645412/111192992-fae9c380-85b9-11eb-9303-8f22240aec77.png)

**Comment by weeco** [comment]
Thanks for testing, I'll take a look at it this weekend and will post an update. When I am able to reproduce the issue, I am sure I can quickly fix this :-).

**Comment by weeco** [comment]
@tewe I was able to reproduce and fix this :-).

**Comment by tewe** [comment]
Works for me. Thanks!

![With newest 2021-03-17 at 10 56 25 AM](https://user-images.githubusercontent.com/645412/111449326-96407d00-870f-11eb-8abb-5265e7da9376.png)

But if I click reload a few times (on the page, not the browser), _sometimes_ the selected start offset gets omitted. New bug?

![Start missing 2021-03-17 at 10 56 37 AM](https://user-images.githubusercontent.com/645412/111449516-c0923a80-870f-11eb-9c9b-9a9243d080e5.png)
