### ISSUE TITLE
Tombstone message

### ISSUE THREAD

**Issue by cobolbaby** [cloudhut/kowl#188]
When previewing a topic with a large number of messages, the recently pushed data is marked as tombstone, which should not have expired yet.

![1587417232](https://user-images.githubusercontent.com/11460848/111270310-aa7e6e80-866a-11eb-917e-2a0b89c4a944.jpg)

**Comment by weeco** [comment]
Hi, this looks like a topic where you are pushing data without key and value. Is that correct? Do you set some headers in there or what's the purpose of pushing records without any data in it?

**Comment by cobolbaby** [comment]
Ohaa, I figured it out. The original table data has been deleted.
