### ISSUE TITLE
Tombstones are not expandable

### ISSUE THREAD

**Issue by weeco** [cloudhut/kowl#192]
As a Kowl user I might want to inspect a message's key (if it's too long to be shown inline) or it's headers even when the value is empty and therefore considered to be a Tombstone. Currently this is not possible because tombstone rows are not expandable as shown here: 
![image](https://user-images.githubusercontent.com/23424570/111902771-4cbd9e00-8a3f-11eb-9a00-205b85ee3e30.png)

Please make a tombstone row expandable as well.

**Comment by rikimaru0345** [comment]
fixed in 0b40fd47dbe6cddeec96a8763768359f36e10529
