### ISSUE TITLE
Rework config pages

### ISSUE THREAD

**Issue by weeco** [cloudhut/kowl#193]
Currently we don't show at what level either a topic config or broker config is set. A topic config entry could be set at the topic level, inherited from the dynamic default broker config, static broker config or even from the kafka default. Additionally we can visually highlight sensitive entrys - currently the sensitive value is just omitted.

When a config entry is different than the default it would also be helpful to know what the default value is, so that the user immediately knows how (much) it differs from the default value.

**Comment by rikimaru0345** [comment]
done in https://github.com/cloudhut/kowl/pull/216
