### ISSUE TITLE
how to disable websockets in kowl ?

### ISSUE THREAD

**Issue by mbulwan** [cloudhut/kowl#195]
Hi,

Does anybody know if there's a way to configure kowl **not to use WebSockets** in environments where websocket protocol is not supported (AWS Classic Load Balancer for example)?   Any fallback to downgrade from websockets to http?

`{"level":"error","ts":"2021-03-31T10:53:30.930Z","msg":"Sending REST error","route":"/api/topics/dev-topic-017/messages","method":"GET","status_code":400,"remote_address":"10.37.40.32","public_error":"Failed upgrade websocket","error":"failed to upgrade websocket in messages endpoint websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header"}`

**Comment by weeco** [comment]
Hi,
no Websockets are required to fetch messages. There's no real workaround , because websockets are pretty handy since we are actually streaming the messages from the backend to the frontend.

**Comment by mbulwan** [comment]
Thank you, Martin, for your prompt response 👍
