### ISSUE TITLE
Preview Column UX requests

### ISSUE THREAD

**Issue by chrisjbremner** [cloudhut/kowl#215]
I just updated to v1.3.1 and am making use of the updates to the preview fields (the improvements are great!). I have two requests that would improve my UX with these fields.

First, would it be possible to wrap preview fields rather than running them off the end of the row? For example, I could imagine that the box in red could be on a new line.

![kowl](https://user-images.githubusercontent.com/15189285/118190262-b9c63200-b3f7-11eb-944f-b07cec81d521.png)

Second, you can see in the image that the preview fields have quite a long name. Would it be possible to truncate the name some way? I could imagine you could allow the user to specify a "nickname" when configuring the preview fields, or it could auto-truncate to something like `top_level_value...matching_field_string`

**Comment by rikimaru0345** [comment]
> First, would it be possible to wrap preview fields rather than running them off the end of the row? For example, I could imagine that the box in red could be on a new line.

Sure, makes sense, I'll add it to my todo.

> Second, you can see in the image...

I don't like truncating. I'd have to essentially make some algorithm to identify what is "less useful" information that I can take out. That's bound to screw up in some cases😂

Giving nicknames to fields is a pretty good idea. I'll do that.

I can't promise when I'll get around to doing those 2 things, but it will probably be "soon" :D

**Comment by chrisjbremner** [comment]
>I don't like truncating. I'd have to essentially make some algorithm to identify what is "less useful" information that I can take out. That's bound to screw up in some cases😂

**Comment by rikimaru0345** [comment]
@chrisjbremner 

I guess this should do it. 😄 
Let me know what you think or if there are any issues.


![chrome_xGTExLxpSZ](https://user-images.githubusercontent.com/28133019/118369580-2d0ca700-b5a4-11eb-90af-90f3500f91f7.png)
![chrome_98hEO1AO85](https://user-images.githubusercontent.com/28133019/118369596-3e55b380-b5a4-11eb-9377-a891d5d9a8af.png)


https://user-images.githubusercontent.com/28133019/118370538-63e4bc00-b5a8-11eb-80f1-df37d13db351.mp4

**Comment by rikimaru0345** [comment]
I'll consider this solved now.
If there's anything else feel free to reopen this issue or create a new one... 😄

**Comment by chrisjbremner** [comment]
Looks great, thank you! There's one minor separate issue with using nesting in the preview fields, but I'll make a new issue for that.

**Comment by chrisjbremner** [comment]
One small other request would be to sort the order of the rows in some deterministic fashion. Currently, if I have a preview with one query that matches two keys, the order in which they are shown is not predictable.

**Comment by rikimaru0345** [comment]
> One small other request would be to sort the order of the rows in some deterministic fashion. Currently, if I have a preview with one query that matches two keys, the order in which they are shown is not predictable.

The feature searches the object in depth-first order.

If you have two tags each yielding one result, the tags are shown in the order you have them in the configuration dialog (that's why they are reorderable).
So in that case you already have full control over the order.

So when a single tag yields multiple results, they are ordered just how they're found, so in depth-first order.

Does that solve your issue?
Or do you want some more options for sorting multiple results from one tag?
And if so, how would it work? Maybe something like alphabetically (which automatically also includes sorting by length)?

**Comment by chrisjbremner** [comment]
Ah ok, in my case I had a single tag, maybe the order of the message itself is the non-deterministic part. Yes, allowing users to select sorting (alphabetically is also what I had in mind) would be nice.

**Comment by chrisjbremner** [comment]
Looks like this fixed my issue, thank you!
