### ISSUE TITLE
Preview field nesting with `.` in key

### ISSUE THREAD

**Issue by chrisjbremner** [cloudhut/kowl#218]
I currently have a message who has a value of:
```
"top_level":{
    "my.nested.key":{
        "value":"test"
    }
}
```

I would like to make a preview tag for `top_level.my.nested.key.value`, but that doesn't work, presumably because it is looking for the following schema instead:

```
"top_level":{
    "my": {
        "nested": {
            "key": {
                "value":"test"
            }
        }
    }
}
```

I'm wondering if there's a different way to denote the nesting besides `.`, or if it could support a regex so I could do something like `top_level\..+\.value`.

**Comment by rikimaru0345** [comment]
There is currently no way to do that.
 
The matching function is super simple and doesn't support stuff like that... And tbh I hate that 😂   Its way too simple and definitely due for a small rework.

The new solution should definitely be able to:
- match keys with dots in them (which is your scenario)
- allow the user to use `*` and maybe also `**` (like file glob patterns). Obviously that should work everywhere, like, support for a `*` in the middle of a string, and not just at the start and end.


I'm currently busy with other stuff though, so it will probably take a day or two until I can start fixing that pattern matching thing. 

Until then, maybe you can give me some feedback on other, related, ideas:
- The little configuration dialog for the preview fields sucks. It is much more difficult than necessary to see what effects your changes have. Maybe we should use a [drawer](https://ant.design/components/drawer/)?? Or something else entirely? 
- Pattern matching also feels a bit limited. Maybe our message has an array, and we want to display only a specific entry? There is no way patter matching can help here. The "patterns" would have to be actual Javascript... But that might be totally overkill, and make it **much** harder for non-programmers to use the feature. 
- As mentioned above: Where do we put the button to open the preview fields configuration, if not in the title of the value column? (Maybe something more unorthodox like not having a button at all, and instead showing the dialog when the user clicks into a cell of the value column?? (But that is probably way too hard to discover for new users))

**Comment by chrisjbremner** [comment]
> The little configuration dialog for the preview fields sucks. It is much more difficult than necessary to see what effects your changes have. Maybe we should use a drawer?? Or something else entirely?

I find the dialog OK, I don't have much of a problem seeing my changes, but that's because I only have a few previews, so I can see the effect below the dialog.

One passing thought is that you could have a dropdown that allows you to select from "pattern" or "schema"? If you select "pattern" you get a text box that you can enter regex/glob (glob would work fine for me, not sure what others' schemas look like). If you select "schema" then you get a [cascader](https://ant.design/components/cascader/) (I like the "custom render" one), which populates its values either from the schema registry, or from pulling the schemas from received messages. Not convinced this is the best idea, yet, though.

> Pattern matching also feels a bit limited. Maybe our message has an array, and we want to display only a specific entry? There is no way patter matching can help here. The "patterns" would have to be actual Javascript... But that might be totally overkill, and make it much harder for non-programmers to use the feature.

Agreed, although JS is already used for filters. I think with similar help tools (basics/parameters/examples), it should be fairly easy for "superusers" to pick up. With https://github.com/cloudhut/kowl/issues/168, you also would have a case for the "user story" of a non-programmer not involving configuring previews at all (unless they wanted different previews that a programmer did, for some reason, but that seems like something you could put behind user roles). I'd be 👍 on JS previews, though.

**Comment by rikimaru0345** [comment]
> If you select "schema" then you get a cascader (I like the "custom render" one),
I like it too, but I can see a few issues with it:
- Its not possible to select a node in the middle (an object, instead of a terminal/leaf)
- When the object is deep, that selection box will probably end up being extremely wide
- In your case, where there are key-names containing dots (or potentially even longer strings), that kind of display might be very tricky to navigate. If there is a key that (for whatever reason) even contains a `\n` things probably will get weird in the cascader box.

As for js preview stuff:
I definitely want to do that eventually. But since there are other, more pressing, issues, it will probably be a while (weeks, months) until I can get around to implementing that. The biggest issue by far isn't the implementation itself, but how to properly design it in the UI. Like making it "discoverable", but not overloading the UI even more...

Now, regarding your actual issue, keys that contain a dot (or anything really):
I guess I'll have to format those kinds of keys just like the js "array" syntax when I internally generate the "path" I match against. Then the pattern would be `top_level["my.nested.key"].value`.

What priority does that have for you? Is this a blocking issue for you, or just a nice to have?
If it's not too important I'll take care of it over the coming weekend or so.

**Comment by chrisjbremner** [comment]
Ah right, all of the cascader stuff makes sense. I figured your first two points would be covered by using a pattern instead, but I hadn't considered there potentially being `\n` inside a key.

This is not a blocking issue for me, I can work around it for now, so it's just a nice to have at the moment. I appreciate you fixing it!

**Comment by rikimaru0345** [comment]
Next version has lots of upgrades to pattern matching in preview tags.

- You can now use quotes (single and double) to quote property names. That fixes your issue with non-standard key names, you can write `a."x.y".b"` and it will be split internally into path segments `a`, `x.y`, `b`

- You can now use glob patterns `**` and `*`
    - All sub objects: `**` 
    - All properties of the current object: `*`
    - Wildcards in a path segment: `data.*ail` would match `data.snail`, `data.mail`, etc. There can be multiple wildcard symbols anywhere in a path segment. But they can't be next to each other like `abc**def` (wouldn't make sense anyway).

**Comment by chrisjbremner** [comment]
Just tried out the glob approach, that works well for me. Thank you for adding this!
