### ISSUE TITLE
Off by one error while display ACL resource pattern type

### ISSUE THREAD

**Issue by jami** [cloudhut/kowl#227]
Hi we have ACLs on our cluster and detected that the "resource-pattern-type to string" for the UI seems to generate false entries

<img width="171" alt="Bildschirmfoto 2021-06-22 um 15 08 58" src="https://user-images.githubusercontent.com/225667/122930198-0cd2c380-d36c-11eb-8bae-ddd15ccda892.png">

All PREFIXED values are LITERAL
All UNKNOWN values are PREFIXED

It tend to be a off by one error

**Comment by rikimaru0345** [comment]
Which build do you use? What git-sha does it show at the very bottom of the page? (might need to scroll down to see it)

**Comment by jami** [comment]
Kowl - v1.4.0
(built Thu May 27 2021)
1177dfd

**Comment by twmb** [comment]
This is likely https://github.com/twmb/franz-go/commit/96cb1c2 which is fixed in v0.8.1 of franz-go

**Comment by jami** [comment]
Current build uses github.com/twmb/franz-go v0.7.6

**Comment by weeco** [comment]
v0.8 has some breaking changes, I'll try to upgrade to that version within the next few days. I'll update this issue once done

**Comment by weeco** [comment]
I just pushed a new commit that uses the latest franz-go (kafka client) version that should contain the fix.
We build a new docker image for each push, so in a few minutes a new one should be available in our Quay repo.
