### ISSUE TITLE
Add exponential backoff for initial startup

### ISSUE THREAD

**Issue by jamesliu4c** [cloudhut/kowl#228]
I am running Kafka using Docker Compose for local development. When I specify Kowl in the docker-compose file, it gives up trying to connect to Kafka before the cluster is ready. If the retry time increased with each retry, it should find a broker eventually.

For now, I say `docker restart kowl` when Kafka is ready.

**Comment by weeco** [comment]
This should be fixed with the newer kafka client we are using. Please let us know in this issue if the issue still persists, then I'll reopen the issue and fix it.
