### ISSUE TITLE
Error when 1 Kafka broker is down

### ISSUE THREAD

**Issue by saryeHaddadi** [cloudhut/kowl#240]
**Issue encountered:** For a given cluster, when at least 1 Kafka broker is down, Kowl returns an error in the UI.
`({"statusCode":500,"message":"Could not describe cluster"} (500 - Internal Server Error)`

**Expected Behaviour:** This is not correct, given that Kafka still works well even if some brokers are down.
I expected that Kowl would still work, and that at most display a warning that a broker is down, but it should still work.

Thanks!

**Comment by weeco** [comment]
Hey @saryeHaddadi ,
you are absolutely right. This is something we worked on in the last releases. Could you let me know what version you used when facing this issue? I don't see this issue in the most recent version anymore, but it surely was happening on v1.3 for instance.

**Comment by saryeHaddadi** [comment]
Hi @weeco, hope you are doing well!

This happened with v1.4.0. Just tried with master, and the issue still happens.
When cliking on "refresh (F5)", the pages display a 500 error. (pages = all of them throw the error, it seems that the schema registry only throws an error time to time).

So this is for a running instance of kowl, then afterward a kafka broker goes down.
I also found another issue. At Kowl initial startup, if the 1st Broker mentionned in Kowl's config is down, Kowl will not start. (But if the broker down is not the first in the config list, Kowl can start).

My setup is: 3 Kafka brokers, and I stop the Kafka service for the 1st or the 2nd broker from Kowl config list.

**Comment by weeco** [comment]
Thanks for the follow up, can you provide the logs from the container / backend? I think they would indicate a bit more detail about what's going on.

I'll try to reproduce the other issue with an offline server in the bootstrap addresses, but it rings some bells. I assume that I have fixed that as well. Maybe you are open for trying the latest master release as well, otherwise I'll get back to you soonish

**Comment by saryeHaddadi** [comment]
Below is a dump of the logs. I tried with the latest master from quay.io.
Another information about our testing environment : we use 3 VM, each hosting a Kafka & a Zookeeper (ie. both on the same box). 

{"level":"warn","ts":"2021-08-12T12:14:44.633Z","msg":"unable to open connection to broker","source":"kafka_client","addr":"SRV-DEVKAFKA02.*******:9092","broker":-2147483647,"err":"dial tcp 10.*.*.*:9092: connect: connection refused"}
{"level":"error","ts":"2021-08-12T12:14:44.633Z","msg":"Sending REST error","route":"/api/kowl/endpoints","method":"GET","status_code":500,"remote_address":"10.*.*.*:2337","public_error":"Could not get cluster config","error":"failed to get kafka api version: unable to dial: dial tcp 10.*.*.*:9092: connect: connection refused"}
{"level":"warn","ts":"2021-08-12T12:14:44.683Z","msg":"unable to open connection to broker","source":"kafka_client","addr":"SRV-DEVKAFKA02.**********:9092","broker":-2147483647,"err":"dial tcp 10.*.*.*:9092: connect: connection refused"}

 {"statusCode":404,"message":"Failed to describe consumer groups: all '1' requests have failed, last error: unable to dial: dial tcp 10.*.*.*:9092: connect: connection refused"} (404 - Not Found)

 {"level":"error","ts":"2021-08-12T12:16:30.703Z","msg":"Sending REST error","route":"/api/kowl/endpoints","method":"GET","status_code":500,"remote_address":"10.*.*.*:12811","public_error":"Could not get cluster config","error":"failed to get kafka api version: unable to dial: dial tcp 10.*.*.*:9092: connect: connection refused"}
{"level":"warn","ts":"2021-08-12T12:16:33.356Z","msg":"unable to open connection to broker","source":"kafka_client","addr":"SRV-DEVKAFKA02.*************:9092","broker":-2147483647,"err":"dial tcp 10.*.*.*:9092: connect: connection refused"}
{"level":"warn","ts":"2021-08-12T12:16:33.356Z","msg":"failed to request kafka version","error":"failed to request api versions: unable to dial: dial tcp 10.*.*.*:9092: connect: connection refused"}

**Comment by weeco** [comment]
Hey, so we have two distinct issues here. Let's first focus on the connection issue with an offline address in the bootstrap server. Can you enable debug logs and paste the full logs here? Feel free to redact the address again

**Comment by saryeHaddadi** [comment]
Hey yes weeco. For this first issue, it tried the tags "master" and "master-e3d61e13".
- Everything seeed to work fine for "master-e3d61e13".
- For Tag "master", here are the debug log.

{"level":"info","ts":"2021-08-13T09:49:00.926Z","msg":"started Kowl","version":"master","git_sha":"2991089d0a3e7271b395b14263502477a826f6ce","built":"2021-06-01T19:56:39Z"}
{"level":"info","ts":"2021-08-13T09:49:00.926Z","msg":"connecting to Kafka seed brokers, trying to fetch cluster metadata"}
{"level":"debug","ts":"2021-08-13T09:49:00.926Z","msg":"opening connection to broker","source":"kafka_client","addr":"hostname-BROKER01:9092","broker":-2147483648}
{"level":"debug","ts":"2021-08-13T09:49:00.938Z","msg":"kafka connection failed","source":"kafka_client_hooks","broker_host":"hostname-BROKER01","error":"dial tcp IP-BROKER01:9092: connect: connection refused"}
{"level":"warn","ts":"2021-08-13T09:49:00.938Z","msg":"unable to open connection to broker","source":"kafka_client","addr":"hostname-BROKER01:9092","broker":-2147483648,"err":"dial tcp IP-BROKER01:9092: connect: connection refused"}
{"level":"fatal","ts":"2021-08-13T09:49:00.938Z","msg":"failed to create kafka service","error":"failed to test kafka connection: failed to request metadata: unable to dial: dial tcp IP-BROKER01:9092: connect: connection refused"}

**Comment by weeco** [comment]
In regards to the connecting error: I just updated the kafka lib to the latest version. Could you check whether this is still an issue with the latest docker image built against master?

In regards to the failed cluster describe I will file a fix soonish and refer this issue in the PR.

**Comment by saryeHaddadi** [comment]
Hi weeco, just tried and the tag 'master' works well.
I think the real the reason why the tag "master" didn't work a few days back, was because [imagePullPolicy ](https://kubernetes.io/docs/concepts/containers/images/#updating-images)is by default set to 'IfNotPresent', so it used an old 'master' in my case.

**Comment by weeco** [comment]
Hey @saryeHaddadi ,
I just tried reproducing it with the latest Kowl version - without success. I believe this may be fixed in one of the newer Kowl versions. Could you retry?

I will close the issue for now (for housekeeping reasons), but I will reopen in case the issues persists

**Comment by saryeHaddadi** [comment]
Hi weeco, I can't test againt, but it was fine for me when I tested and poster my last comment, so it's okay. Thank you
