### ISSUE TITLE
Timed out requests sometimes do not return the results

### ISSUE THREAD

**Issue by weeco** [cloudhut/kowl#25]
For some requests Kafka Owl times out because the Kafka Cluster does not deliver the responses in a timely manner. The UI shows that it has aborted the request after 20s:

```
Backend API Error
Please check and modify the request before resubmitting.
Request '/api/topics/__consumer_offsets/messages?_offsetMode=-1&startOffset=-1&partitionID=94&pageSize=50&sortOrder=0&sortType=0' timed out after 20.0 sec
```

**The backend logs:**

```json
{"level":"error","ts":"2019-12-27T09:50:50.433Z","msg":"Request was cancelled while waiting for messages from workers (probably timeout)","completedWorkers":0,"startedWorkers":1,"fetchedMessages":24}
```

It was expected that the backend returns the 24 fetched messages (all messages until the request context is cancelled) to the frontend, along with a flag that the request did not complete because it expired this timeout threshold.

The frontend should show the timeout properly as well (if it doesn't do so already).

**Comment by weeco** [comment]
This has likely been resolved as the whole list messages flow has been rewritten and changed to websockets.

**Comment by anvaari** [comment]
@weeco 
The same thing happened on  v23.3 when I wanted to load some message with a `timestamp` search in the big topic. 
![image](https://github.com/redpanda-data/console/assets/39170783/3a23df0c-9c00-4a73-a185-ad3a7de5aec1)

**Comment by weeco** [comment]
@anvaari How long did the request take? Do you see error logs in Console? Is it the cluster that takes too long to answer the request to resolve an offset for a given timestamp? If so please create an issue in the redpanda repository instead, ideally with a way to how reproduce this.

If you are a customer I recommend reaching out via the usual support channels.

**Comment by anvaari** [comment]
> @anvaari How long did the request take? Do you see error logs in Console? Is it the cluster that takes too long to answer the request to resolve an offset for a given timestamp? If so please create an issue in the redpanda repository instead, ideally with a way to how reproduce this.
> 
> If you are a customer I recommend reaching out via the usual support channels.

I use redpanda consol for managing our Kafka Cluster. Yes it take time for cluster to respond the request. It take 30 seconds. Is there any config to increase this timeout ?

**Comment by weeco** [comment]
Please raise an issue in the redpanda repository, looking up an offset by timestamp shouldn't take so long.

**Comment by anvaari** [comment]
But I don't connect to Redpana, I connect to Kafka. Is that ok to raise there?

**Comment by weeco** [comment]
In that case you should either talk to your Kafka vendor or try to raise it via the community channels.

**Comment by anvaari** [comment]
So there isn't any option to increase the timeout, right ?
