### ISSUE TITLE
Error in connect server

### ISSUE THREAD

**Issue by klinux** [cloudhut/kowl#251]
I'm receiving this error when try to access connect server:

 {"statusCode":503,"message":"Failed to get cluster info: invalid character 'U' looking for beginning of value"} (503 - )

The connect server use basic authentication. It is supported by kowl?

Thank you

**Comment by weeco** [comment]
Hi yes it's supported, see the reference config: https://github.com/cloudhut/kowl/blob/9f50ebad9e639658764b01c9de60b7f2b10cfca9/docs/config/kowl.yaml#L128-L129

**Comment by klinux** [comment]
Yes, I had configured it, but the error is the same, I will try to investigate here to discovery what happening.

Thank you

**Comment by klinux** [comment]
Curious, even I'm setting username and password, kowl send request without authorization header:

```
GET /connectors?expand=info&expand=status HTTP/1.1
Host: cp-kafka-connect:8083
User-Agent: Kowl
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip

HTTP/1.1 401 Unauthorized
Date: Thu, 02 Sep 2021 23:55:07 GMT
Content-Type: application/json
Content-Length: 32
Server: Jetty(9.4.40.v20210413)

User cannot access the resource.
```

**Comment by klinux** [comment]
I believe this behavior has relation with this file in module **connect-client:** https://github.com/cloudhut/connect-client/blob/main/client.go.

**SetBasicAuth** is commented.

```go
	c.client = resty.New().
		SetHostURL(c.hostURL).
		SetHeader("User-Agent", c.userAgent).
		SetHeader("Accept", "application/json").
		SetHeader("Content-Type", "application/json").
		SetTimeout(c.timeout).
		SetError(&ApiError{}).
		// SetBasicAuth(c.username, c.password).
		SetAuthToken(c.authToken).
		SetTLSClientConfig(c.tlsCfg)

	return c
```

**Comment by weeco** [comment]
Thanks for a taking a look into this and filing this issue in the first place. I patched the client and updated the dependency in Kowl :).
