### ISSUE TITLE
Message metadata - Json data classified as type "Avro"

### ISSUE THREAD

**Issue by saryeHaddadi** [cloudhut/kowl#253]
Hi!

I have a topic containing Json data, published by Kafka Connect linked to the Schema Registry.
In the Schema Registry topic (_schemas), the type of the subject is Json :

```
{
"subject":"DEV.SHA.test_connect-value"
"version":1
"id":18
"schemaType":"JSON"
"schema":"{"type":"string"}"
"deleted":false
}
```

However, the topic's messages are displayed as being of type "Avro".
- Also, in case of an empty message (0 charactere), the type is displayed as "Text", I don't know if this is an error, but I expected that all messages would be of their subject's type, ie Json.

![image](https://user-images.githubusercontent.com/51054901/132359715-7070f18c-f46a-42f6-99c6-c67d61aa2da6.png)

**Comment by weeco** [comment]
JSON schema support has been added already, so I'm closing this.
