### ISSUE TITLE
Cannot read properties of null (reading 'length')

### ISSUE THREAD

**Issue by ricecombo5** [cloudhut/kowl#263]
Type:
TypeError

Message:
Cannot read properties of null (reading 'length')

Stack (Decoded):
render (components/pages/consumers/Group.Details.tsx:66:98)
sum (utils/arrayExtensions.ts:102:43)
sum (utils/arrayExtensions.ts:102:16)
render (components/pages/consumers/Group.Details.tsx:66:74)
allowStateChanges<T> (../../src/core/action.ts:149:15)
reactiveRender (../../src/observerClass.ts:134:28)
Array (../../src/core/derivation.ts:177:21)
isSpyEnabled (../../src/core/reaction.ts:137:23)
reactiveRender (../../src/observerClass.ts:132:8)

Stack (Raw):
TypeError: Cannot read properties of null (reading 'length')
    at https://kowl03.in.obsec.io/static/js/main.366aafe9.chunk.js:1:252151
    at https://kowl03.in.obsec.io/static/js/main.366aafe9.chunk.js:1:4148
    at Array.reduce (<anonymous>)
    at Array.sum (https://kowl03.in.obsec.io/static/js/main.366aafe9.chunk.js:1:4117)
    at n.value (https://kowl03.in.obsec.io/static/js/main.366aafe9.chunk.js:1:252112)
    at Le (https://kowl03.in.obsec.io/static/js/2.c77d56f0.chunk.js:2:13359)
    at https://kowl03.in.obsec.io/static/js/2.c77d56f0.chunk.js:2:65736
    at Xe (https://kowl03.in.obsec.io/static/js/2.c77d56f0.chunk.js:2:19292)
    at e.t.track (https://kowl03.in.obsec.io/static/js/2.c77d56f0.chunk.js:2:23628)
    at n.l [as render] (https://kowl03.in.obsec.io/static/js/2.c77d56f0.chunk.js:2:65701)

Components:

    at n (https://kowl03.in.obsec.io/static/js/main.366aafe9.chunk.js:1:251171)
    at t (https://kowl03.in.obsec.io/static/js/2.c77d56f0.chunk.js:2:116535)
    at t (https://kowl03.in.obsec.io/static/js/2.c77d56f0.chunk.js:2:117486)
    at s (https://kowl03.in.obsec.io/static/js/2.c77d56f0.chunk.js:2:861432)
    at h (https://kowl03.in.obsec.io/static/js/2.c77d56f0.chunk.js:2:862141)
    at Xt
    at n (https://kowl03.in.obsec.io/static/js/main.366aafe9.chunk.js:1:302928)
    at main
    at h (https://kowl03.in.obsec.io/static/js/2.c77d56f0.chunk.js:2:528946)
    at a (https://kowl03.in.obsec.io/static/js/2.c77d56f0.chunk.js:2:528776)
    at section
    at https://kowl03.in.obsec.io/static/js/2.c77d56f0.chunk.js:2:529206
    at a (https://kowl03.in.obsec.io/static/js/2.c77d56f0.chunk.js:2:528776)
    at l (https://kowl03.in.obsec.io/static/js/2.c77d56f0.chunk.js:2:62025)
    at section
    at https://kowl03.in.obsec.io/static/js/2.c77d56f0.chunk.js:2:529206
    at a (https://kowl03.in.obsec.io/static/js/2.c77d56f0.chunk.js:2:528776)
    at t (https://kowl03.in.obsec.io/static/js/2.c77d56f0.chunk.js:2:116535)
    at t (https://kowl03.in.obsec.io/static/js/2.c77d56f0.chunk.js:2:117486)
    at n (https://kowl03.in.obsec.io/static/js/main.366aafe9.chunk.js:1:314272)
    at n (https://kowl03.in.obsec.io/static/js/main.366aafe9.chunk.js:1:346303)
    at t (https://kowl03.in.obsec.io/static/js/2.c77d56f0.chunk.js:2:113829)
    at t (https://kowl03.in.obsec.io/static/js/2.c77d56f0.chunk.js:2:563547)

Environment:
NODE_ENV : production
GIT_SHA  : 1177dfdcda669904b0fbfc54934dbeba322bf2af
GIT_REF  : v1.4.0
TIMESTAMP: 1622141499
appName  : Kowl

Location:
Protocol: https:
Path    : /groups/elastic_persistence-vpqdpaoeqxxzdvjd-activity20200513
Search  : 
Hash    :

**Comment by weeco** [comment]
Hi @ricecombo5 ,
can you take a look at the backend logs and paste them there as well?

**Comment by ricecombo5** [comment]
@weeco  I don't see the backend logging anything when the above error occurred.  I'm pasting the content of the log file anyway but not sure if they correlate.

```
kowl03-7f55bfcc8d-hbd52 kowl {"level":"warn","ts":"2021-09-15T16:22:01.871Z","msg":"read from broker errored, killing connection after 0 successful responses (is sasl missing?)","source":"kafka_client","addr":"b-1.data-kafka-three.sbc76k.c1.kafka.us-west-2.amazonaws.com:9094","id":-2147483647,"err":"context deadline exceeded"}
kowl03-7f55bfcc8d-hbd52 kowl {"level":"error","ts":"2021-09-15T16:22:01.871Z","msg":"could not describe topic configs","error":"context deadline exceeded"}
kowl03-7f55bfcc8d-hbd52 kowl {"level":"warn","ts":"2021-09-15T16:22:01.871Z","msg":"failed to fetch topic configs to return cleanup.policy","error":"failed to request topic configs: context deadline exceeded"}
kowl03-7f55bfcc8d-hbd52 kowl {"level":"error","ts":"2021-09-15T17:47:48.304Z","msg":"failed to request topic offsets","error":"the internal broker struct chosen to issue this requesthas died--either the broker id is migrating or no longer exists"}
kowl03-7f55bfcc8d-hbd52 kowl {"level":"error","ts":"2021-09-15T17:47:48.304Z","msg":"could not describe topic configs","error":"context deadline exceeded"}
kowl03-7f55bfcc8d-hbd52 kowl {"level":"warn","ts":"2021-09-15T17:47:48.304Z","msg":"failed to fetch topic configs to return cleanup.policy","error":"failed to request topic configs: context deadline exceeded"}
kowl03-7f55bfcc8d-hbd52 kowl {"level":"error","ts":"2021-09-15T17:47:48.304Z","msg":"failed to request topic offsets","error":"the internal broker struct chosen to issue this requesthas died--either the broker id is migrating or no longer exists"}
kowl03-7f55bfcc8d-hbd52 kowl {"level":"error","ts":"2021-09-15T17:47:48.304Z","msg":"failed to request partition marks in bulk","error":"failed to request topic offsets: the internal broker struct chosen to issue this requesthas died--either the broker id is migrating or no longer exists"}
kowl03-7f55bfcc8d-hbd52 kowl {"level":"warn","ts":"2021-09-15T17:50:13.798Z","msg":"read from broker errored, killing connection after 0 successful responses (is sasl missing?)","source":"kafka_client","addr":"b-3.data-kafka-three.sbc76k.c1.kafka.us-west-2.amazonaws.com:9094","id":-2147483646,"err":"context deadline exceeded"}
kowl03-7f55bfcc8d-hbd52 kowl {"level":"error","ts":"2021-09-15T17:50:13.798Z","msg":"could not describe topic configs","error":"context deadline exceeded"}
kowl03-7f55bfcc8d-hbd52 kowl {"level":"warn","ts":"2021-09-15T17:50:13.798Z","msg":"failed to fetch topic configs to return cleanup.policy","error":"failed to request topic configs: context deadline exceeded"}
kowl03-7f55bfcc8d-hbd52 kowl {"level":"warn","ts":"2021-09-15T17:53:01.184Z","msg":"read from broker errored, killing connection after 0 successful responses (is sasl missing?)","source":"kafka_client","addr":"b-3.data-kafka-three.sbc76k.c1.kafka.us-west-2.amazonaws.com:9094","id":3,"err":"context deadline exceeded"}
kowl03-7f55bfcc8d-hbd52 kowl {"level":"error","ts":"2021-09-15T17:53:01.184Z","msg":"could not describe topic configs","error":"context deadline exceeded"}
kowl03-7f55bfcc8d-hbd52 kowl {"level":"warn","ts":"2021-09-15T17:53:01.184Z","msg":"failed to fetch topic configs to return cleanup.policy","error":"failed to request topic configs: context deadline exceeded"}
kowl03-7f55bfcc8d-hbd52 kowl {"level":"warn","ts":"2021-09-15T17:54:37.428Z","msg":"read from broker errored, killing connection after 0 successful responses (is sasl missing?)","source":"kafka_client","addr":"b-2.data-kafka-three.sbc76k.c1.kafka.us-west-2.amazonaws.com:9094","id":2,"err":"context deadline exceeded"}
kowl03-7f55bfcc8d-hbd52 kowl {"level":"error","ts":"2021-09-15T17:54:37.429Z","msg":"could not describe topic configs","error":"context deadline exceeded"}
kowl03-7f55bfcc8d-hbd52 kowl {"level":"warn","ts":"2021-09-15T17:54:37.429Z","msg":"failed to fetch topic configs to return cleanup.policy","error":"failed to request topic configs: context deadline exceeded"}





kowl03-7f55bfcc8d-hbd52 kowl {"level":"warn","ts":"2021-09-15T18:28:54.664Z","msg":"read from broker errored, killing connection after 0 successful responses (is sasl missing?)","source":"kafka_client","addr":"b-1.data-kafka-three.sbc76k.c1.kafka.us-west-2.amazonaws.com:9094","id":1,"err":"context deadline exceeded"}
kowl03-7f55bfcc8d-hbd52 kowl {"level":"error","ts":"2021-09-15T18:28:54.664Z","msg":"could not describe topic configs","error":"context deadline exceeded"}
kowl03-7f55bfcc8d-hbd52 kowl {"level":"warn","ts":"2021-09-15T18:28:54.664Z","msg":"failed to fetch topic configs to return cleanup.policy","error":"failed to request topic configs: context deadline exceeded"}
```

**Comment by ricecombo5** [comment]
@weeco until this is addressed, is there a server-side timeout setting that we could extend to minimize this type of errors?

**Comment by weeco** [comment]
@ricecombo5 , no I'd recommend contact Amazon if you are using MSK. I have never seen such timeouts before, I believe this kind of data is usually cached and we usually experience responses in the magnitude of milliseconds. 

Is the issue reproducible or does it happen sporadically? In either way the response you would see in the frontend is probably not satisfying.

**Comment by ricecombo5** [comment]
@weeco This error only happens on some of the consumer groups and when a consumer group has this error, it'd present the same error every time I view the consumer group.  

Regarding the "context deadline exceeded", I noticed it'd timeout around 6 seconds.  I'm not too familiar with the code base but possibly it's pointing to https://github.com/cloudhut/kowl/blob/45718679d74aa8d8108dab5e668d44c50b65f470/backend/pkg/owl/cluster_info.go#L44 ?

**Comment by weeco** [comment]
@ricecombo5 Can you please test whether this still happens with the latest version? We haven't implemented something specific for this, but since we touched that codeportion there might be a chance that this doesn't happen anymore.

If it still does I'll have a look. Ideally you could send us the API Response (see network tab in dev tools) as that might help to spot potential issues.

**Comment by ricecombo5** [comment]
@weeco we're running on the latest(?) v1.4.0.  Here's a sample response from the UI hitting `/api/topics` endpoint

```json
...
{
        "topicName": "[removed xxxxx]",
        "isInternal": false,
        "partitionCount": 1,
        "replicationFactor": 3,
        "cleanupPolicy": "N/A",
        "logDirSummary": {
            "totalSizeBytes": 0
        },
        "allowedActions": ["all"]
    }, {
        "topicName": "[removed xxxxxx]",
        "isInternal": false,
        "partitionCount": 1,
        "replicationFactor": 3,
        "cleanupPolicy": "N/A",
        "logDirSummary": {
            "totalSizeBytes": 252714,
            "replicaErrors": [{
                "brokerId": 3,
                "error": "the internal broker struct chosen to issue this requesthas died--either the broker id is migrating or no longer exists"
            }],
            "hint": "Topic size is an estimate because the size of 1 partitions was estimated"
        },
        "allowedActions": ["all"]
    }
....

```

**Comment by weeco** [comment]
Here you can find the latest versions built against master: https://quay.io/repository/cloudhut/kowl?tab=tags

**Comment by ricecombo5** [comment]
@weeco latest version quay.io/cloudhut/kowl:master stills shows 
```
"msg": "could not describe topic configs","error":"context deadline exceeded"
```

**Comment by weeco** [comment]
@ricecombo5 That's per se not an issue. That basically just means that the Kafka request timed out. Most likely that's an issue with your Kafka cluster.

**Comment by ricecombo5** [comment]
@weeco right.  We have 3 clusters.  The two clusters with 6k partitions and 12k partitions seem to work fine since the request to `/api/topics` take under 3 seconds.  However, our largest cluster has about 36k partitions and it seems to fail to fetch within the allotted 6(?) seconds.  If I remember correctly, it started to fail when the cluster grew to about 25k partitions.  Can we make this "6 second" configurable so `/api/topics` doesn't timeout for large clusters? 
And/or possibly bump the 6-second default to let's say 15-second so most "large" clusters would work out-of-the-box without additional configuration tweaks?

**Comment by weeco** [comment]
@ricecombo5 What you linked is just one specific endpoint. I'm running Kowl on clusters with more than 50k partitions without problems. These responses should come pretty fast regardless of the partition count I think. I'm sure there are more users that run Kowl against very large clusters. When even the Describe command for a topic fails I'd be really concerned. Have you tried describing some topics with the Kafka cli and see if that fails / takes very long?

The problem is that the more likely case (that a broker is offline/unreachable) we would need to wait for this max time. That's only for describing the log dir size though.

**Comment by ricecombo5** [comment]
@weeco fair enough.  You're probably correct.  Will investigate the topics, consumers health on our cluster.

**Comment by vector-mj** [comment]
I have the same issue in v1.5.0 and v1.4.0
Image: quay.io/cloudhut/kowl

**Comment by weeco** [comment]
@vector-mj this is a very old version. Please update to the latest Redpanda Console (rebranded Kowl) version
