### ISSUE TITLE
Schema registry not configured

### ISSUE THREAD

**Issue by sardar-ji** [cloudhut/kowl#264]
Hi,

I am running kowl as docker container with below command:

docker run -it -d --name kafka-ui -p 8080:8080 -e KAFKA_BROKERS=localhost:9092 quay.io/cloudhut/kowl:master

But when I open the UI, I get this message that schema registry is not configured. How to configure schema registry?

**Comment by weeco** [comment]
Hi,
did you see the reference config?
https://github.com/cloudhut/kowl/blob/master/docs/config/kowl.yaml

Even though it's given in the YAML format, at the top there's documentation how each variable is configurable as ENV variable as well.
