### ISSUE TITLE
Incorrect assigned partitions number?

### ISSUE THREAD

**Issue by cemremengu** [cloudhut/kowl#273]
The members part of the consumer groups and the top level "Assigned Partitions" show that all partitions are assigned. However, the members sections shows that not all partitions are assigned for topics (I expect 2 for each since each of these topics has 2 partitions).

Is this a bug in UI or my system? 😕 

![image](https://user-images.githubusercontent.com/1297759/139571986-dbb8297a-5537-45c7-a317-1b8d5d452ff9.png)

![image](https://user-images.githubusercontent.com/1297759/139572038-bc40ca42-5247-4332-bf89-33f508a5b64d.png)

**Comment by cemremengu** [comment]
There was an issue with my system so the topics section was correct but still confused about members section

**Comment by weeco** [comment]
@cemremengu Can you explain what you are confused about?

**Comment by cemremengu** [comment]
In the top picture (section), the `request.icmp.status` topic is shown as having 1 partition assigned (partition 0). However, the second picture `request.icmp.status` is shown that both of its partitions (0 and 1 respectively) are assigned.

**Comment by weeco** [comment]
@cemremengu I understand and you are right that this is wrong. I was not able to reproduce this with the latest version. Is this something you can consistently reproduce?

**Comment by cemremengu** [comment]
I was able to reproduce it consistently before I fixed my code but not anymore. My (java/spring-kafka) producer was not sending messages to all partitions so some of them were being left unassigned.  I was hitting [this bug](https://issues.apache.org/jira/browse/KAFKA-9965) and switching to `UniformStickyPartitioner` solved to problem. 

Maybe this also affects kowl? By the way thank you so much for your work on this project, it is the best I have seen so far and saved me a lot of time.

**Comment by weeco** [comment]
@cemremengu Okay that explains a few things. The assignments are stored by the client in a standardized format as a byte array along with the Consumer Group. Kowl just decodes the GroupMemberMetadata and visualizes it accordingly. Basically the consumer members write what we are supposed to show in Kowl. See: https://github.com/cloudhut/kowl/blob/ce13b2b75962ec8adfad318aea87861624a8dc2a/backend/pkg/owl/consumer_group_overview.go#L160-L175

Thanks for the nice words, I'm glad you like it and that it helps you. Goal achieved :).
