### ISSUE TITLE
Support Kafka secured with SSL

### ISSUE THREAD

**Issue by pchrzasz** [cloudhut/kowl#279]
Cannot find in docs any mention regarding that. Is it possible to connect to Kafka cluster secured with SSL (acl based on cert DN) via kowl passing trustore/keystore location and password via env variables or anything else?

**Comment by weeco** [comment]
@pchrzasz If you mean mutual TLS have a look at https://github.com/cloudhut/kowl/blob/0b9e3672f15db9435cc1fa1e0a9da96b6d2cfe6f/docs/config/kowl.yaml#L55-L61

**Comment by pchrzasz** [comment]
@weeco This is exactly what I was looking for. Thank you :)
