### ISSUE TITLE
Time estimate of azure active directory support?

### ISSUE THREAD

**Issue by iamvibhorsingh** [cloudhut/kowl#285]
Currently, the documentation states that azure active directory support is planned but there is no time estimate mentioned for it anywhere (that i could find). Would it be possible to get a rough time estimate for this integration?

Thanks!

**Comment by weeco** [comment]
Hey @iamvibhorsingh ,
we are currently not actively working on this, but this came up recently as well. It seems like Azure AD supports OpenID connect so that implementing support for it shouldn't take longer than a week.

**Comment by iamvibhorsingh** [comment]
Thanks for the quick reply! Definitely looking forward to when you guys implement it.

**Comment by weeco** [comment]
Azure AD support has been merged and is available as part of the Redpanda Enterprise offering.
