### ISSUE TITLE
Messages filter does not support UTF-8

### ISSUE THREAD

**Issue by javalover123** [cloudhut/kowl#303]
Messages filter does not support UTF-8.

![image](https://user-images.githubusercontent.com/9191388/149618399-ce424e3c-5a61-4e84-87a7-e42ef75113ce.png)

**Comment by rikimaru0345** [comment]
Hi, I need to reproduce this.
For that, can you post the message-value and the filter you used?

**Comment by javalover123** [comment]
Message is: {"en":"abcde","cn":"我爱你中国"}
Filter is: return value.cn.includes("福")
