### ISSUE TITLE
Preview Fields can't be reordered

### ISSUE THREAD

**Issue by rikimaru0345** [cloudhut/kowl#31]
Current (really bad) workarounds:
- Delete tag, add it back again (new tags get added to the end)
- Open chrome dev tools; in local storage select the key `uiSettings`; inside the json navigate into `topicList`, then `previewTags`; then manually change stuff there; reload page
  
Fix is simple and likely won't take much time, just use something like:
https://github.com/clauderic/react-sortable-hoc/blob/master/examples/basic.js

**Comment by chrisjbremner** [comment]
They also don't appear to be editable in the event that you make a typo

**Comment by weeco** [comment]
Fixed in v1.3.0 ; autocomplete is also available now.
