### ISSUE TITLE
KsqlDB support 

### ISSUE THREAD

**Issue by OuesFa** [cloudhut/kowl#310]
Hello 👋 
Is there any plan to add a tab in order to make queries to ksqlDB clusters? Like the one for Kafka Connect & Schema Registry.
Thanks

**Comment by weeco** [comment]
Hey @OuesFa ,
I think there's already one such request: https://github.com/cloudhut/kowl/issues/177 . Can we close this issue in favour of the older issue?

Currently we haven't prioritized it yet, but I recommend voting it by adding your thumbs up reaction to that issue. We usually try to prioritize what the community wants to see :). Thanks for letting us know what you'd like to see!
