### ISSUE TITLE
SCRAM-SHA-512 not working with MSK SASL_SSL

### ISSUE THREAD

**Issue by tonyqiu2020** [cloudhut/kowl#322]
I have a MSK cluster, enabled username password auth. It works fine when I have for example kafka-connect with settings like this

```
  kafkastore.security.protocol: "SASL_SSL",
  kafkastore.sasl.mechanism: "SCRAM-SHA-512",
  kafkastore.sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username='alice' password='alice-secret';
```
But when use kowl to configure 

 ```    
      sasl:
        enabled: true
        username: alice
        password: alice-secret
        mechanism: SCRAM-SHA-512 
```

It give me the error 

msg":"unable to initialize sasl","source":"kafka_client","broker":"seed 0","err":"Authentication failed during authentication due to invalid credentials with SASL mechanism SCRAM-SHA-512: SASL_AUTHENTICATION_FAILED: SASL Authentication failed."}

**Comment by weeco** [comment]
Hey @tonyqiu2020 ,
I'm afraid that I don't have an immediate idea what the reason for this could be. Your provided configuration looks correct (e.g. mechanism name for scram sha512) and since you said that it works with Kafka connect I would assume that the broker behaves correctly as well.

I would recommend to turn on debug logging and look for specific things there. Of course we do not print the password in the logs, so I would additionally double check whether the provided password is set correctly (keep in mind that the password can be inherited from environment variables or flags and that they take priority over YAMl config).

Other than that I currently don't have any good suggestions to further debug this. If you have the chance to attach a debugger to the backend my next try (if these attempts failed) is to attach the debugger during the configuration of the kafka client. I have tested SCRAM-SHA-256 several times with success, and MSK_IAM was also already reported as a success with AWS MSK. I'm not so sure about SCRAM-SHA-512, but I haven't heard about issues with it yet.

**Comment by weeco** [comment]
One more idea: Can you setup a SCRAM-SHA-256 user/password and try that? It's worth a try because we know that Kowl works with SCRAM-SHA-256.  Maybe that yields some more insights

**Comment by tonyqiu2020** [comment]
@weeco Thanks for the quick response. 

-  Yes. I did enable SSL explicitly
-  I tried SCRAM-SHA-256 and it says

``` │ {"level":"info","ts":"2022-02-24T19:47:27.792Z","msg":"connecting to Kafka seed brokers, trying to fetch cluster metadata"}                                                                                              ││ {"level":"error","ts":"2022-02-24T19:47:28.116Z","msg":"unable to initialize sasl","source":"kafka_client","broker":"seed 0","err":"UNSUPPORTED_SASL_MECHANISM: The broker does not support the requested SASL mechanism ││ {"level":"fatal","ts":"2022-02-24T19:47:28.116Z","msg":"failed to create kafka service","error":"failed to test kafka connection: failed to request metadata: UNSUPPORTED_SASL_MECHANISM: The broker does not support th ││                                                                                                                                                                                                                          ```
- MSK_IAM did work for me. But since other things like confluent kafka connect works better on SASL_SSL SCRAM-SHA-512, that is why I like to make that work on kowl as well. 

Could you guide me on how to enable debug mode?

**Comment by weeco** [comment]
> I tried SCRAM-SHA-256 and it says

You also have to enable that mechanism on the broker if you want to try that.

> Could you guide me on how to enable debug mode?

You can configure the logger config as part of the Kowl config: https://github.com/cloudhut/kowl/blob/898f908b7e99bcfecce2a9e38ec5674de861d920/docs/config/kowl.yaml#L173-L174

**Comment by tonyqiu2020** [comment]
Amazon MSK only supports SCRAM-SHA-512 authentication. 

Here is the debug message with SCRAM-SHA-512 

```
{"level":"info","ts":"2022-02-25T13:24:48.977Z","msg":"started Kowl","version":"v1.5.0","git_sha":"598117cf7d3ef49e82ad9e7424a08858b3e60216","built":"2021-11-10T21:41:16Z"}                                                                                                                                             │
│ {"level":"debug","ts":"2022-02-25T13:24:48.977Z","msg":"configuring SCRAM-SHA-512 mechanism"}                                                                                                                                                                                                                            │
│ {"level":"info","ts":"2022-02-25T13:24:48.977Z","msg":"connecting to Kafka seed brokers, trying to fetch cluster metadata"}                                                                                                                                                                                              │
│ {"level":"debug","ts":"2022-02-25T13:24:48.977Z","msg":"opening connection to broker","source":"kafka_client","addr":"b-1.demo-cluster-1.k9y22l.c20.kafka.us-east-1.amazonaws.com:9096","broker":"seed 0"}                                                                                                               │
│ {"level":"debug","ts":"2022-02-25T13:24:48.995Z","msg":"connection opened to broker","source":"kafka_client","addr":"b-1.demo-cluster-1.k9y22l.c20.kafka.us-east-1.amazonaws.com:9096","broker":"seed 0"}                                                                                                                │
│ {"level":"debug","ts":"2022-02-25T13:24:48.995Z","msg":"issuing api versions request","source":"kafka_client","broker":"seed 0","version":3}                                                                                                                                                                             │
│ {"level":"debug","ts":"2022-02-25T13:24:48.995Z","msg":"wrote ApiVersions v3","source":"kafka_client","broker":"seed 0","bytes_written":31,"write_wait":0.000020198,"time_to_write":0.0000415,"err":null}                                                                                                                │
│ {"level":"debug","ts":"2022-02-25T13:24:48.995Z","msg":"read ApiVersions v3","source":"kafka_client","broker":"seed 0","bytes_read":366,"read_wait":0.000049149,"time_to_read":0.000607425,"err":null}                                                                                                                   │
│ {"level":"debug","ts":"2022-02-25T13:24:48.995Z","msg":"issuing SASLHandshakeRequest","source":"kafka_client","broker":"seed 0"}                                                                                                                                                                                         │
│ {"level":"debug","ts":"2022-02-25T13:24:48.996Z","msg":"wrote SASLHandshake v1","source":"kafka_client","broker":"seed 0","bytes_written":33,"write_wait":0.000012347,"time_to_write":0.000030144,"err":null}                                                                                                            │
│ {"level":"debug","ts":"2022-02-25T13:24:48.996Z","msg":"read SASLHandshake v1","source":"kafka_client","broker":"seed 0","bytes_read":29,"read_wait":0.000034683,"time_to_read":0.000567058,"err":null}                                                                                                                  │
│ {"level":"debug","ts":"2022-02-25T13:24:48.996Z","msg":"beginning sasl authentication","source":"kafka_client","broker":"seed 0","mechanism":"SCRAM-SHA-512","authenticate":true}                                                                                                                                        │
│ {"level":"debug","ts":"2022-02-25T13:24:48.996Z","msg":"issuing SASLAuthenticate","source":"kafka_client","broker":"seed 0","version":2,"step":0}                                                                                                                                                                        │
│ {"level":"debug","ts":"2022-02-25T13:24:48.996Z","msg":"wrote SASLAuthenticate v2","source":"kafka_client","broker":"seed 0","bytes_written":62,"write_wait":0.000020151,"time_to_write":0.000033386,"err":null}                                                                                                         │
│ {"level":"debug","ts":"2022-02-25T13:24:48.997Z","msg":"read SASLAuthenticate v2","source":"kafka_client","broker":"seed 0","bytes_read":124,"read_wait":0.000028414,"time_to_read":0.000793877,"err":null}                                                                                                              │
│ {"level":"debug","ts":"2022-02-25T13:24:49.000Z","msg":"issuing SASLAuthenticate","source":"kafka_client","broker":"seed 0","version":2,"step":1}                                                                                                                                                                        │
│ {"level":"debug","ts":"2022-02-25T13:24:49.001Z","msg":"wrote SASLAuthenticate v2","source":"kafka_client","broker":"seed 0","bytes_written":150,"write_wait":0.000012311,"time_to_write":0.000032853,"err":null}                                                                                                        │
│ {"level":"debug","ts":"2022-02-25T13:24:49.340Z","msg":"read SASLAuthenticate v2","source":"kafka_client","broker":"seed 0","bytes_read":126,"read_wait":0.000029864,"time_to_read":0.33950351,"err":null}                                                                                                               │
│ {"level":"error","ts":"2022-02-25T13:24:49.340Z","msg":"unable to initialize sasl","source":"kafka_client","broker":"seed 0","err":"Authentication failed during authentication due to invalid credentials with SASL mechanism SCRAM-SHA-512: SASL_AUTHENTICATION_FAILED: SASL Authentication failed."}                  │
│ {"level":"debug","ts":"2022-02-25T13:24:49.340Z","msg":"connection initialization failed","source":"kafka_client","addr":"b-1.demo-cluster-1.k9y22l.c20.kafka.us-east-1.amazonaws.com:9096","broker":"seed 0","err":"Authentication failed during authentication due to invalid credentials with SASL mechanism SCRAM-SH │
│ {"level":"fatal","ts":"2022-02-25T13:24:49.340Z","msg":"failed to create kafka service","error":"failed to test kafka connection: failed to request metadata: Authentication failed during authentication due to invalid credentials with SASL mechanism SCRAM-SHA-512: SASL_AUTHENTICATION_FAILED: SASL Authentication  │
│```

**Comment by tonyqiu2020** [comment]
Maybe related to this https://github.com/twmb/franz-go/issues/136?

**Comment by twmb** [comment]
@tonyqiu2020 I have a suspicion as to what this is, actually. Kowl v1.5 was released in Nov and is using franz-go v1.2.3. I noticed something not correct w.r.t. scram and fixed it in v1.2.5: https://github.com/twmb/franz-go/blob/master/CHANGELOG.md#v125 (commit https://github.com/twmb/franz-go/commit/03c58cb)

I wonder if it may be that. Kafka proper was not validating the s-nonce in the client final reply, but I wonder if MSK is. cc @weeco

**Comment by tonyqiu2020** [comment]
I just tried the latest mater image (which has franz-go 1.2.7), same errors.

**Comment by twmb** [comment]
Is it possible to connect with kcat with these same credentials? I'd like to narrow down if this is a problem with franz-go (and other clients can connect), or if this is a problem on Amazon's end.

What I do know is that scram as provided by franz-go works, and sha256 vs sha512 is a difference in the name and the new function (and that's it). Not sure why it'd fail against Amazon.

**Comment by tonyqiu2020** [comment]
@twmb Yes. I confirmed it works well with kcat (I need to ignore SSL ca verification)

```
root@my-shell:/# kafkacat -b $BROKERS -C -X enable.ssl.certificate.verification=false -X security.protocol=SASL_SSL -X sasl.mechanisms=SCRAM-SHA-512 -X sasl.username=$USERNAME -X sasl.password=$PASSWORD -t connect-configs
```

**Comment by twmb** [comment]
Ah right I forgot that the opening comment showed it working in Java.

Would it be possible to try kcl, with --log-level debug? https://github.com/twmb/kcl/

I think you'd need `-X sasl.method=scram-sha-512 -X sasl.user=<> -X sasl.pass=<>` 

This would help narrow down if it's something within kowl or within franz-go (last check).

**Comment by tonyqiu2020** [comment]
OK. kcl works with settings like this

```
seed_brokers = ["b-1.demo-cluster-1.xxxx.kafka.us-east-1.amazonaws.com:9096"]
timeout_ms = 10000

[tls]

[sasl]
  method = "scram-sha-512"
  user = "xxx"
  pass = "xxx-xxxx"
  is_token = false
```

I also noticed that if is_token is true, it shows the same error log. I wonder if somehow is_token is set to true here?

**Comment by weeco** [comment]
Hey @tonyqiu2020 ,
thank you for being so persistent with this. I have double checked the code and it still looks right me, the only possible issue I can imagine now is the config parsing. Therefore I just added another debug logging that will print the kafka config that is passed into the code that creates the franz-go client instance. If you could try the latest docker image (currently being built, see: https://github.com/cloudhut/kowl/actions/runs/1953351735) with debug logs enabled that would be nice. Particularly I'm interested whether the logged kafka config prints what you expect.

Other than that I have also updated the franz-go (the Kafka library) dependency to the latest version.

Thanks again!

**Comment by tonyqiu2020** [comment]
There is log, and for some reason, it is not well formatted json. I assume password has been reacted. I cannot find something wrong about configuration though. 

```
{"level":"info","ts":"2022-03-08T19:36:19.563Z","msg":"started Kowl","version":"master","git_sha":"015a86d46d7ac104e8d516755b99479f657710de","built":"2022-03-08T19:15:41Z"}
{"level":"debug","ts":"2022-03-08T19:36:19.564Z","msg":"creating new kafka client","config":{"Brokers":["b-1.demo-cluster-1.k9y22l.c20.kafka.us-east-1.amazonaws.com:9096","b-2.demo-cluster-1.k9y22l.c20.kafka.us-east-1.amazonaws.com:9096","b-3.demo-cluster-1.k9y22l.c20.kafka.us-east-1.amazonaws.com:9096"[],"ClientID":"kowl","ClusterVersion":"1.0.0","RackID":"","Schema":{"Enabled":true,"URLs":["http://my-schema-registry-cp-schema-registry:8081"],"Username":"","Password":"","BearerToken":"","TLS":{"Enabled":false,"CaFilepath":"","CertFilepath":"","KeyFilepath":"","InsecureSkipTLSVerify":false}},"Protobuf":{"enabled":false,"schemaRegistry":{"enabled":false,"refreshInterval":300000000000},"git":{"Enabled":false,"AllowedFileExtensions":["proto"[],"MaxFileSize":500000,"IndexByFullFilepath":true,"RefreshInterval":60000000000,"Repository":{"URL":"","Branch":"","BaseDirectory":"."},"BasicAuth":{"Enabled":false,"Username":"","Password":""},"SSH":{"Enabled":false,"Username":"","PrivateKey":"","PrivateKeyFilePath":"","Passphrase":""}},"fileSystem":{"Enabled":false,"AllowedFileExtensions":["proto"[],"MaxFileSize":500000,"IndexByFullFilepath":true,"RefreshInterval":300000000000,"Paths":null},"mappings":null},"MessagePack":{"Enabled":false,"TopicNames":["/.*/"]},"TLS":{"Enabled":true,"CaFilepath":"","CertFilepath":"","KeyFilepath":"","Passphrase":"","InsecureSkipTLSVerify":false},"SASL":{"Enabled":true,"Username":"alice","Password":"","Mechanism":"SCRAM-SHA-512","OAUth":{"Token":""},"GSSAPIConfig":{"AuthType":"","KeyTabPath":"","KerberosConfigPath":"","ServiceName":"","Username":"","Password":"","Realm":"","EnableFast":true},"AWSMskIam":{"AccessKey":"","SecretKey":"","SessionToken":"","UserAgent":""}}}}
{"level":"debug","ts":"2022-03-08T19:36:19.564Z","msg":"configuring SCRAM-SHA-512 mechanism"}
{"level":"info","ts":"2022-03-08T19:36:19.564Z","msg":"connecting to Kafka seed brokers, trying to fetch cluster metadata"}
{"level":"debug","ts":"2022-03-08T19:36:19.564Z","msg":"opening connection to broker","source":"kafka_client","addr":"b-1.demo-cluster-1.k9y22l.c20.kafka.us-east-1.amazonaws.com:9096","broker":"seed 0"}
{"level":"debug","ts":"2022-03-08T19:36:19.583Z","msg":"kafka connection succeeded","source":"kafka_client_hooks","host":"b-1.demo-cluster-1.k9y22l.c20.kafka.us-east-1.amazonaws.com","dial_duration":0.019287047}
{"level":"debug","ts":"2022-03-08T19:36:19.583Z","msg":"connection opened to broker","source":"kafka_client","addr":"b-1.demo-cluster-1.k9y22l.c20.kafka.us-east-1.amazonaws.com:9096","broker":"seed 0"}
{"level":"debug","ts":"2022-03-08T19:36:19.583Z","msg":"issuing api versions request","source":"kafka_client","broker":"seed 0","version":3}
{"level":"debug","ts":"2022-03-08T19:36:19.583Z","msg":"wrote ApiVersions v3","source":"kafka_client","broker":"seed 0","bytes_written":31,"write_wait":0.000021394,"time_to_write":0.000034101,"err":null}
{"level":"debug","ts":"2022-03-08T19:36:19.584Z","msg":"read ApiVersions v3","source":"kafka_client","broker":"seed 0","bytes_read":366,"read_wait":0.000043713,"time_to_read":0.000751064,"err":null}
{"level":"debug","ts":"2022-03-08T19:36:19.584Z","msg":"issuing SASLHandshakeRequest","source":"kafka_client","broker":"seed 0"}
{"level":"debug","ts":"2022-03-08T19:36:19.584Z","msg":"wrote SASLHandshake v1","source":"kafka_client","broker":"seed 0","bytes_written":33,"write_wait":0.000029292,"time_to_write":0.000068564,"err":null}
{"level":"debug","ts":"2022-03-08T19:36:19.585Z","msg":"read SASLHandshake v1","source":"kafka_client","broker":"seed 0","bytes_read":29,"read_wait":0.000074037,"time_to_read":0.000578372,"err":null}
{"level":"debug","ts":"2022-03-08T19:36:19.585Z","msg":"beginning sasl authentication","source":"kafka_client","broker":"seed 0","mechanism":"SCRAM-SHA-512","authenticate":true}
{"level":"debug","ts":"2022-03-08T19:36:19.585Z","msg":"issuing SASLAuthenticate","source":"kafka_client","broker":"seed 0","version":2,"step":0}
{"level":"debug","ts":"2022-03-08T19:36:19.585Z","msg":"wrote SASLAuthenticate v2","source":"kafka_client","broker":"seed 0","bytes_written":61,"write_wait":0.000035006,"time_to_write":0.000027024,"err":null}
{"level":"debug","ts":"2022-03-08T19:36:19.587Z","msg":"read SASLAuthenticate v2","source":"kafka_client","broker":"seed 0","bytes_read":122,"read_wait":0.000028692,"time_to_read":0.001933023,"err":null}
{"level":"debug","ts":"2022-03-08T19:36:19.591Z","msg":"issuing SASLAuthenticate","source":"kafka_client","broker":"seed 0","version":2,"step":1}
{"level":"debug","ts":"2022-03-08T19:36:19.591Z","msg":"wrote SASLAuthenticate v2","source":"kafka_client","broker":"seed 0","bytes_written":174,"write_wait":0.00001144,"time_to_write":0.000031318,"err":null}
{"level":"debug","ts":"2022-03-08T19:36:19.892Z","msg":"read SASLAuthenticate v2","source":"kafka_client","broker":"seed 0","bytes_read":126,"read_wait":0.000030574,"time_to_read":0.301354917,"err":null}
{"level":"error","ts":"2022-03-08T19:36:19.892Z","msg":"unable to initialize sasl","source":"kafka_client","broker":"seed 0","err":"Authentication failed during authentication due to invalid credentials with SASL mechanism SCRAM-SHA-512: SASL_AUTHENTICATION_FAILED: SASL Authentication failed."}
{"level":"debug","ts":"2022-03-08T19:36:19.892Z","msg":"connection initialization failed","source":"kafka_client","addr":"b-1.demo-cluster-1.k9y22l.c20.kafka.us-east-1.amazonaws.com:9096","broker":"seed 0","err":"Authentication failed during authentication due to invalid credentials with SASL mechanism SCRAM-SHA-512: SASL_AUTHENTICATION_FAILED: SASL Authentication failed."}
{"level":"debug","ts":"2022-03-08T19:36:19.892Z","msg":"kafka broker disconnected","source":"kafka_client_hooks","host":"b-1.demo-cluster-1.k9y22l.c20.kafka.us-east-1.amazonaws.com"}
{"level":"fatal","ts":"2022-03-08T19:36:19.892Z","msg":"failed to create kafka service","error":"failed to test kafka connection: failed to request metadata: Authentication failed during authentication due to invalid credentials with SASL mechanism SCRAM-SHA-512: SASL_AUTHENTICATION_FAILED: SASL Authentication failed."}
```

**Comment by weeco** [comment]
@tonyqiu2020 actually the password should only be redacted if it is set, see: https://github.com/cloudhut/kowl/blob/015a86d46d7ac104e8d516755b99479f657710de/backend/pkg/kafka/config.go#L76-L94

Therefore I believe that the password is actually not set here for whatever reason. From looking at your original post it seems you configure it with YAML is that right? I couldn't spot an issue with this and I also use the YAML configuration in my local setups without problem. Do you possibly override the password by specifying an environment variable or flag?

**Comment by tonyqiu2020** [comment]
I finally got it working! So basically in yml, put password in kowl/config/sasl section will not work but put under secret/kakfa works.

```
kowl:
  # See reference config: https://github.com/cloudhut/kowl/blob/master/docs/config/kowl.yaml)
  config:
    kafka:
      brokers:
        - xxx:9096
      sasl:
        enabled: true
        username: alice
        password: xxx
```

```
secret:
  kafka: 
    saslPassword: xxx
```

Thanks a lot @weeco and @twmb

**Comment by weeco** [comment]
Oh you used the helm chart? That makes sense to me then. Thanks for letting us know!

**Comment by mattiadevivo** [comment]
> I finally got it working! So basically in yml, put password in kowl/config/sasl section will not work but put under secret/kakfa works.
> 
> ```
> kowl:
>   # See reference config: https://github.com/cloudhut/kowl/blob/master/docs/config/kowl.yaml)
>   config:
>     kafka:
>       brokers:
>         - xxx:9096
>       sasl:
>         enabled: true
>         username: alice
>         password: xxx
> ```
> 
> ```
> secret:
>   kafka: 
>     saslPassword: xxx
> ```
> 
> Thanks a lot @weeco and @twmb

Thank you, I was just facing the same issue while deploying kowl using the helm chart against AWS MSK with SASL SCRAM-SHA-512 enabled

**Comment by contre95** [comment]
> I finally got it working! So basically in yml, put password in kowl/config/sasl section will not work but put under secret/kakfa works.
> 
> ```
> kowl:
>   # See reference config: https://github.com/cloudhut/kowl/blob/master/docs/config/kowl.yaml)
>   config:
>     kafka:
>       brokers:
>         - xxx:9096
>       sasl:
>         enabled: true
>         username: alice
>         password: xxx
> ```
> 
> ```
> secret:
>   kafka: 
>     saslPassword: xxx
> ```
> 
> Thanks a lot @weeco and @twmb

Hey, sorry to comment into this old thread. Is there a solution here were we can pass the password as an ENV variables ? I can't see the `secret_kafka_saslPassword` on the console configuration.
I'm having this exact same issue of `UNSUPPORTED_SASL_MECHANISM: The broker does not support the requested SASL mechanism` but I'm not using HELM, I'm running this on AWS ECS against AWS MSK and sending the vars through environment variables.
