### ISSUE TITLE
Topic documentation: code blocks, HTML not rendered

### ISSUE THREAD

**Issue by DavidPratt512** [cloudhut/kowl#323]
Hey all, love the project.

When documenting a topic with a markdown file, the text inside any code blocks are not present on the webpage. Additionally, HTML inside the markdown file shows on the webpage as text. See below:

**topic.md**:

    # Topic Docs
    
    Test docs with `inline code`.
    <br/>
    We've even got
    ```
    $ code blocks
    ```

**Kowl**:
![image](https://user-images.githubusercontent.com/26131314/156295682-ac42e624-3a29-49a2-993e-9c19ef41ac23.png)

The interesting thing is that the `<code>` and `<pre>` HTML blocks are present on the page - they just have no text inside them.

As an aside, I'm not too concerned with the HTML inside the markdown file being unusable. I just expected it to work like most other markdown renderers.

Not sure if this is related to the "TODO" in #121.

**Comment by weeco** [comment]
Hey @DavidPratt512 ,
we escape HTML on purpose for security reasons, but the normal markdown syntax for inline code and code blocks should work just fine. I will need to have a look why this is not working, I hope I will be able to reproduce this.

I'm very time constrained at the moment, but I hope I can have a look at this weekend. Feel free to ping me if you haven't received a response by next week. Thanks for filing this 👍
