### ISSUE TITLE
Degrade `/groups` gracefully during rolling update of kafka brokers

### ISSUE THREAD

**Issue by rikimaru0345** [cloudhut/kowl#39]
Similar to issue #35, viewing consumer-groups also does not work as intended when not all kafka brokers are available (for example when they are being restarted one-by-one by a rolling update)

- [ ] Backend should degrade gracefully (show as much info as possible, instead of returning a status:500)
- [ ] Frontend should be able to handle `.lag == null` and show an icon in place of the missing information
- [ ] HTTP error messages should be shown in the frontend. Currently the 'message' of `statusCode: 500, 
message: "Could not describe consumer groups in the Kafka cluster"` is not shown at all.

**Comment by weeco** [comment]
A more robust handling is available since v1.3.0
