### ISSUE TITLE
Make admin page useful

### ISSUE THREAD

**Issue by rikimaru0345** [cloudhut/kowl#53]
- When viewing a user, the roles/permissions are shown, but the page should also show how the user got that role! Specifically: what binding caused this role to be added to the user?

- Which groups is a given user part of (directly, and indirectly)?
- Who is in a given group?

- Bug: Clicking on the + in the bindings table expands all lines
- Bug: The expand icon is at the wrong position

- Issue: Users Tab: space should not be distributed that way. In every column there's only very little text, and when each column is 1/3 of the width, the rows are hard to read because the values are so far apart. There should be an empty column on the right that takes up all the remaining space.

**Comment by weeco** [comment]
I think we should also rework the `roles` tab. We could make it a normal table where each row can be expanded. Only the expanded version would then show the full role definition. 

![Table example](https://i.imgur.com/2gZU2l1.png)
