### ISSUE TITLE
Proper support for displaying `key`

### ISSUE THREAD

**Issue by rikimaru0345** [cloudhut/kowl#78]
We now have `keyType` in each message.
The UI has no support for showing binary data yet though (always shown as raw/ascii).

- user should be able to select the format the "key" column shows:  raw, base64, hex-bytes
- don't show raw by default when the type is known to be binary

**Comment by rikimaru0345** [comment]
Good example is the `__consumer_offsets` topic.

The same issue actually also applies to `value`! The user should be able to change that as well.
Also the preview is hex, while the expanded data is ascii...

**Comment by weeco** [comment]
Resolved in v1.3.0
