### ISSUE TITLE
Small issues in message filter UX

### ISSUE THREAD

**Issue by rikimaru0345** [cloudhut/kowl#92]
- filter editor needs a close button
- it should be more obvious whether a filter is active/inactive and how to switch it
    - maybe an info icon next to the + button that explains it
    - should also explain that multiple filters are combined with &&
    - and (one or more) examples that show each parameter being used
- docu/info display says the parameter name is `partitionID` but it should say `partitionId`

**Comment by weeco** [comment]
some more ideas for improving the ux of message filters:

- frontend continously checks whether the javascript code is valid (if this isn't possible in the frontend we can add a dedicated endpoint for this in the backend)
- some sort of live preview of the filter results based on the last search results?
- intellisense would be the nonplusultra but is probably a big effort to implement (maybe this becomes easier when we have the schema generation for JSON ready?)

**Comment by weeco** [comment]
Superseded by https://github.com/cloudhut/kowl/issues/212
