### ISSUE TITLE
Option to edit consumer group offsets

### ISSUE THREAD

**Issue by weeco** [cloudhut/kowl#95]
**Usecase**

I'd like to have an option to edit the offsets of specific Consumer Groups in a comfortable way. Common scenarios are:

- I want to edit the offset of a single partition within a topic
- I want to edit the offsets for all partitions of a single topic (e.g. set to "Earliest" or "Latest" or entirely remove the offsets)
- I want to edit all group offsets (earliest/latest/remove) at once

Kowl should make sure that the consumer group is inactive to prevent offset overwriting from active consumers.

**Comment by rikimaru0345** [comment]
With all edit functionality we'll have to protect against cross-site scripting.

**Comment by weeco** [comment]
Fixed via https://github.com/cloudhut/kowl/commit/7931c138410ad17bc22c9c1c1afabcc047c204d8
